In [9]:
import pandas as pd
import glob
import os

In [10]:
# Define the path to your directory containing Excel files
# You can use a wildcard '*' to match all Excel files (.xlsx or .xls): 
# 
csv_files_path = "C:/Users/ukhan/Documents/DataSet/OpenMesh/nceia_noaa/"

## Merge 2023 and 2024 New york data from lat lon

In [3]:
nyc_2023_csv = "2023_lat_40_6__40_8__lon_-74_01__-73_92_nyc_22K_1.csv"
nyc_2024_csv = "2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_21K_1.csv"

In [11]:
nyc_2023_csv = "2023_lat_40_6__40_8__lon_-74_01__-73_92_nyc_22K_1_22cols.csv"
nyc_2024_csv = "2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_21K_1_22cols.csv"

In [12]:
nyc_2023_df = pd.read_csv(csv_files_path+nyc_2023_csv)

In [13]:
nyc_2024_df = pd.read_csv(csv_files_path+nyc_2024_csv)

In [14]:
nyc_2023_df.shape

(22117, 22)

In [15]:
nyc_2024_df.shape

(21824, 22)

In [16]:
nyc_2023_df.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL', 'WND', 'CIG',
       'VIS', 'TMP', 'DEW', 'SLP', 'GD1', 'GE1', 'GF1', 'MA1', 'REM',
       'source_file'],
      dtype='object')

In [17]:
## Combiner 2023 + 2024 data
combined_df = pd.concat([nyc_2023_df, nyc_2024_df], ignore_index=True)

In [18]:
combined_df.shape

(43941, 22)

In [19]:
combined_df.head()

,STATION,DATE,SOURCE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,CALL_SIGN,QUALITY_CONTROL,...,VIS,TMP,DEW,SLP,GD1,GE1,GF1,MA1,REM,source_file
0,72055399999,2023-01-01T00:05:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-16,99999,V020,...,"000805,1,9,9","+9999,9","+9999,9","99999,9","4,99,1,+00091,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,00091,1,99,9,99,9","10108,1,99999,9",MET071SPECI KJRB 010005Z AUTO 00000KT 1/2SM FG...,72055399999.csv
1,72055399999,2023-01-01T00:17:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-16,99999,V020,...,"001609,1,9,9","+9999,9","+9999,9","99999,9","4,99,1,+00091,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,00091,1,99,9,99,9","10108,1,99999,9",MET082SPECI KJRB 010017Z AUTO 25006KT 1SM -RA ...,72055399999.csv
2,72055399999,2023-01-01T00:20:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-16,99999,V020,...,"004023,1,9,9","+9999,9","+9999,9","99999,9","4,99,1,+00091,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,00091,1,99,9,99,9","10108,1,99999,9",MET086SPECI KJRB 010020Z AUTO 25005KT 2 1/2SM ...,72055399999.csv
3,72055399999,2023-01-01T00:27:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-16,99999,V020,...,"001609,1,9,9","+9999,9","+9999,9","99999,9","4,99,1,+00091,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,00091,1,99,9,99,9","10108,1,99999,9",MET099SPECI KJRB 010027Z AUTO 24005KT 1SM UP O...,72055399999.csv
4,72055399999,2023-01-01T00:32:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-16,99999,V020,...,"000805,1,9,9","+9999,9","+9999,9","99999,9","4,99,1,+00091,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,00091,1,99,9,99,9","10108,1,99999,9",MET091SPECI KJRB 010032Z AUTO 22004KT 1/2SM UP...,72055399999.csv

In [20]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43941 entries, 0 to 43940
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATION          43941 non-null  int64
 1   DATE             43941 non-null  object
 2   SOURCE           43941 non-null  int64
 3   LATITUDE         43941 non-null  float64
 4   LONGITUDE        43941 non-null  float64
 5   ELEVATION        43941 non-null  float64
 6   NAME             43941 non-null  object
 7   REPORT_TYPE      43941 non-null  object
 8   CALL_SIGN        43941 non-null  object
 9   QUALITY_CONTROL  43941 non-null  object
 10  WND              43941 non-null  object
 11  CIG              43941 non-null  object
 12  VIS              43941 non-null  object
 13  TMP              43941 non-null  object
 14  DEW              43941 non-null  object
 15  SLP              43941 non-null  object
 16  GD1              34440 non-null  object
 17  GE1              24207 non-null  object
 18  GF1              41728 non-null  object
 19  MA1              43168 non-null  object
 20  REM              43940 non-null  object
 21  source_file      43941 non-null  object
dtypes: float64(3), int64(2), object(17)
memory usage: 7.4+ MB

In [21]:
combined_df.shape

(43941, 22)

In [22]:
combined_df.to_csv(csv_files_path+"2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K.csv", index=False)

In [22]:
combined_df.to_csv(csv_files_path+"2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_22cols.csv", index=False)

## Checkpoint#1: 2023-2024 44K RAW Data on lat-lon position

In [69]:
combined_df = pd.read_csv(csv_files_path+"2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K.csv")

In [134]:
combined_df = pd.read_csv(csv_files_path+"2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_22cols.csv")

In [135]:
combined_df.shape

(43941, 22)

In [136]:
combined_df.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL', 'WND', 'CIG',
       'VIS', 'TMP', 'DEW', 'SLP', 'GD1', 'GE1', 'GF1', 'MA1', 'REM',
       'source_file'],
      dtype='object')

### Process date Time to dateTime format for plotting time-series data

In [137]:
combined_df.DATE = pd.to_datetime(combined_df.DATE)

In [138]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43941 entries, 0 to 43940
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATION          43941 non-null  int64
 1   DATE             43941 non-null  datetime64[ns]
 2   SOURCE           43941 non-null  int64
 3   LATITUDE         43941 non-null  float64
 4   LONGITUDE        43941 non-null  float64
 5   ELEVATION        43941 non-null  float64
 6   NAME             43941 non-null  object
 7   REPORT_TYPE      43941 non-null  object
 8   CALL_SIGN        43941 non-null  object
 9   QUALITY_CONTROL  43941 non-null  object
 10  WND              43941 non-null  object
 11  CIG              43941 non-null  object
 12  VIS              43941 non-null  object
 13  TMP              43941 non-null  object
 14  DEW              43941 non-null  object
 15  SLP              43941 non-null  object
 16  GD1              34440 non-null  object
 17  GE1              24207 non-null  object
 18  GF1              41728 non-null  object
 19  MA1              43168 non-null  object
 20  REM              43940 non-null  object
 21  source_file      43941 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(2), object(16)
memory usage: 7.4+ MB

In [139]:
combined_df.shape

(43941, 22)

In [140]:
from datetime import datetime
start_date = datetime.strptime("10/29/2023 0:00", "%m/%d/%Y %H:%M")
end_date = datetime.strptime("7/1/2024 0:00", "%m/%d/%Y %H:%M")

In [141]:
combined_df = combined_df[combined_df['DATE'].between(start_date, end_date, inclusive='both')]

In [142]:
combined_df.shape

(14727, 22)

In [143]:
combined_df.head(1)

,STATION,DATE,SOURCE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,CALL_SIGN,QUALITY_CONTROL,...,VIS,TMP,DEW,SLP,GD1,GE1,GF1,MA1,REM,source_file
8513,72055399999,2023-10-29 00:56:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-15,99999,V020,...,"016093,1,9,9","+0228,1","+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",MET087METAR KJRB 290056Z AUTO 00000KT 10SM OVC...,72055399999.csv

In [144]:
combined_df.tail(1)

,STATION,DATE,SOURCE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,CALL_SIGN,QUALITY_CONTROL,...,VIS,TMP,DEW,SLP,GD1,GE1,GF1,MA1,REM,source_file
38210,72505394728,2024-06-30 23:51:00,7,40.77898,-73.96925,42.7,"NY CITY CENTRAL PARK, NY US",FM-15,KNYC,V030,...,"003219,5,N,5","+0228,5","+0217,5","10111,5","0,99,1,+99999,9,9",NaN,"00,99,1,99,9,99,9,99999,9,99,9,99,9","10122,5,10064,5",MET11806/30/24 18:51:02 METAR KNYC 302351Z VRB...,72505394728.csv

In [145]:
combined_df.shape

(14727, 22)

In [146]:
combined_df.drop_duplicates().shape

(14727, 22)

In [147]:
combined_df = combined_df.drop_duplicates(subset=['DATE'], keep='first')  ##keep=False|'first'|'last'

In [148]:
combined_df.shape

(14647, 22)

In [149]:
combined_df['CALL_SIGN'].value_counts()

KNYC     7723
99999    6924
Name: CALL_SIGN, dtype: int64

In [150]:
combined_df.QUALITY_CONTROL.value_counts()

V020    7940
V030    6707
Name: QUALITY_CONTROL, dtype: int64

In [151]:
for col in combined_df.columns:
    print("Column", col)
    print(combined_df[col].value_counts())
    print("####################################")

Column STATION
72505394728    7748
72055399999    6899
Name: STATION, dtype: int64
####################################
Column DATE
2023-10-29 00:56:00    1
2024-01-27 02:21:00    1
2024-01-27 03:51:00    1
2024-01-27 04:17:00    1
2024-01-27 04:51:00    1
                      ..
2024-02-07 20:56:00    1
2024-02-07 21:56:00    1
2024-02-07 22:56:00    1
2024-02-07 23:56:00    1
2024-06-30 23:51:00    1
Name: DATE, Length: 14647, dtype: int64
####################################
Column SOURCE
7    6994
4    6924
6     729
Name: SOURCE, dtype: int64
####################################
Column LATITUDE
40.778980    7748
40.701214    6899
Name: LATITUDE, dtype: int64
####################################
Column LONGITUDE
-73.969250    7748
-74.009028    6899
Name: LONGITUDE, dtype: int64
####################################
Column ELEVATION
42.70    7748
2.13     6899
Name: ELEVATION, dtype: int64
####################################
Column NAME
NY CITY CENTRAL PARK, NY US                      7748
PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US    6899
Name: NAME, dtype: int64
####################################
Column REPORT_TYPE
FM-15    11580
FM-16     2822
SOD        245
Name: REPORT_TYPE, dtype: int64
####################################
Column CALL_SIGN
KNYC     7723
99999    6924
Name: CALL_SIGN, dtype: int64
####################################
Column QUALITY_CONTROL
V020    7940
V030    6707
Name: QUALITY_CONTROL, dtype: int64
####################################
Column WND
999,9,C,0000,5    1231
999,9,V,0015,5     760
999,9,C,0000,1     748
999,9,V,0021,5     639
999,9,N,9999,9     558
                  ...
250,1,N,0072,1       1
040,1,V,0051,1       1
260,5,V,0051,5       1
060,1,V,0046,1       1
180,5,V,0051,5       1
Name: WND, Length: 1050, dtype: int64
####################################
Column CIG
22000,5,9,N    4016
22000,1,9,N    2743
00213,1,9,N     295
99999,9,9,9     245
00152,5,M,N     229
               ...
00427,5,W,N       2
00061,5,W,N       2
00457,5,W,N       1
00396,5,W,N       1
00091,5,W,N       1
Name: CIG, Length: 138, dtype: int64
####################################
Column VIS
016093,1,9,9    5465
016093,5,N,5    5128
004828,5,N,5     348
006437,5,N,5     261
004023,5,N,5     252
999999,9,9,9     246
014484,1,9,9     234
014484,5,N,5     209
008047,5,N,5     190
012875,5,N,5     188
009656,5,N,5     178
004828,1,9,9     171
011265,5,N,5     162
008047,1,9,9     145
006437,1,9,9     145
003219,5,N,5     144
012875,1,9,9     133
002816,5,N,5     132
009656,1,9,9     130
011265,1,9,9     128
004023,1,9,9     125
003219,1,9,9      83
002414,5,N,5      65
002012,5,N,5      53
002816,1,9,9      51
001207,5,N,5      43
001609,5,N,5      41
001207,1,9,9      31
000805,5,N,5      24
002414,1,9,9      23
001609,1,9,9      21
002012,1,9,9      17
000402,5,N,5      15
000805,1,9,9      15
003219,5,V,5      10
002816,5,V,5       9
004023,5,V,5       9
999999,9,N,A       7
000402,1,9,9       6
000805,A,N,A       3
000402,A,N,A       2
001207,5,V,5       2
016093,1,N,5       1
016093,1,N,A       1
002414,5,V,5       1
Name: VIS, dtype: int64
####################################
Column TMP
+0100,5    334
+0083,5    276
+0089,5    263
+0106,5    255
+0061,5    254
          ...
+0344,1      1
+0090,A      1
-0083,5      1
+0110,A      1
+0220,5      1
Name: TMP, Length: 211, dtype: int64
####################################
Column DEW
+9999,9    286
+0050,1    219
+0067,5    206
+0061,5    193
-0006,5    189
          ...
-0090,5      1
-0040,7      1
-0194,5      1
+0240,5      1
-0080,5      1
Name: DEW, Length: 202, dtype: int64
####################################
Column SLP
99999,9    3118
10161,5      46
10163,5      43
10168,1      42
10164,1      41
           ...
10373,1       1
10383,1       1
10377,1       1
10363,1       1
09989,5       1
Name: SLP, Length: 938, dtype: int64
####################################
Column GD1
0,99,1,+99999,9,9    2847
4,99,1,+00152,5,9     209
4,99,1,+00213,1,9     173
4,99,1,+00122,5,9     166
4,99,1,+00183,5,9     164
                     ...
2,99,1,+02591,9,9       1
2,99,1,+00945,1,9       1
1,99,1,+01433,1,9       1
3,99,1,+00091,1,9       1
4,99,1,+00091,5,1       1
Name: GD1, Length: 540, dtype: int64
####################################
Column GE1
9,AGL   ,+99999,+99999    8406
Name: GE1, dtype: int64
####################################
Column GF1
00,99,1,99,9,99,9,99999,9,99,9,99,9    5500
99,99,9,99,9,99,9,00213,1,99,9,99,9     482
99,99,9,99,9,99,9,00244,1,99,9,99,9     417
99,99,9,99,9,99,9,00274,1,99,9,99,9     396
99,99,9,99,9,99,9,00183,1,99,9,99,9     359
                                       ...
02,99,5,99,9,99,9,00853,1,99,9,99,9       1
02,99,5,99,9,99,9,00122,1,99,9,99,9       1
09,99,1,99,9,99,9,00091,1,99,9,99,9       1
04,99,5,99,9,99,9,00914,1,99,9,99,9       1
04,99,5,99,9,99,9,01006,1,99,9,99,9       1
Name: GF1, Length: 193, dtype: int64
####################################
Column MA1
10169,5,10112,5    161
10179,5,10122,5    147
10176,1,99999,9    146
10176,5,10118,5    145
10173,1,99999,9    139
                  ...
99999,9,99999,9      1
09902,5,09845,5      1
09881,5,09825,5      1
09858,5,09801,5      1
10396,1,99999,9      1
Name: MA1, Length: 348, dtype: int64
####################################
Column REM
MET087METAR KJRB 290056Z AUTO 00000KT 10SM OVC060 23/16 A3005 RMK AO2 SLP176 T02280156 PNO $=                                   1
MET10201/26/24 21:21:01 SPECI KNYC 270221Z 30003KT 4SM BR OVC006 07/06 A3010 RMK AO2 CIG 003V009 T00720056 $                    1
MET09701/26/24 22:51:01 METAR KNYC 270351Z 03003KT 5SM BR SCT007 07/05 A3009 RMK AO2 SLP183 T00670050 $                         1
MET09001/26/24 23:17:02 SPECI KNYC 270417Z 00000KT 5SM BR BKN008 07/05 A3010 RMK AO2 T00670050 $                                1
MET10701/26/24 23:51:02 METAR KNYC 270451Z 03003KT 4SM BR OVC008 07/05 A3011 RMK AO2 SLP188 T00670050 400780056 $               1
                                                                                                                               ..
MET097METAR KJRB 072056Z AUTO 06005KT 10SM CLR 10/M04 A3026 RMK AO2 SLP246 6//// T01001044 56009 PNO $=                         1
MET085METAR KJRB 072156Z AUTO VRB03KT 10SM CLR 09/M03 A3027 RMK AO2 SLP250 T00941028 PNO $=                                     1
MET085METAR KJRB 072256Z AUTO 14003KT 10SM CLR 08/M04 A3028 RMK AO2 SLP255 T00781039 PNO $=                                     1
MET109METAR KJRB 072356Z AUTO 26004KT 10SM CLR 06/M02 A3030 RMK AO2 SLP260 6//// T00611022 10106 20061 53014 PNO $=             1
MET11806/30/24 18:51:02 METAR KNYC 302351Z VRB03KT 2SM BR CLR 23/22 A2989 RMK AO2 SLP111 60016 T02280217 10294 20222 55001 $    1
Name: REM, Length: 14647, dtype: int64
####################################
Column source_file
72505394728.csv    7748
72055399999.csv    6899
Name: source_file, dtype: int64
####################################

In [75]:
columns_not_relevant_for_modeling=['STATION', 'SOURCE', 'ELEVATION', 'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL', 'REM', 'source_file']

In [152]:
#22 columns Columns not relevant for data modelling, carries missing information as per 
#FEDERAL CLIMATE COMPLEX DATA DOCUMENTATION FOR INTEGRATED SURFACE DATA (ISD)
columns_not_relevant_for_modeling=['STATION', 'SOURCE', 'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL', 'REM', 'source_file']

In [153]:
combined_df = combined_df.drop(columns=columns_not_relevant_for_modeling)

In [154]:
combined_df.shape

(14647, 14)

In [155]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,WND,CIG,VIS,TMP,DEW,SLP,GD1,GE1,GF1,MA1
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"999,9,C,0000,1","01829,1,9,N","016093,1,9,9","+0228,1","+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9"
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"999,9,V,0021,1","22000,5,9,N","016093,1,9,9","+0211,1","+0133,1","10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9"
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"999,9,C,0000,1","22000,5,9,N","016093,1,9,9","+0200,1","+0106,1","10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9"
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"040,1,N,0026,1","22000,5,9,N","016093,1,9,9","+0189,1","+0100,1","10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9"
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"999,9,V,0021,1","02438,1,9,N","016093,1,9,9","+0178,1","+0094,1","10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9"

In [156]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'WND', 'CIG', 'VIS',
       'TMP', 'DEW', 'SLP', 'GD1', 'GE1', 'GF1', 'MA1'],
      dtype='object')

### Process and extract numeric data

##### Process WND column

* POS: 61-63
WIND-OBSERVATION direction angle
The angle, measured in a clockwise direction, between true north and the direction from which the wind is blowing.
MIN: 001 MAX: 360 UNITS: Angular Degrees
SCALING FACTOR: 1
DOM: A general domain comprised of the numeric characters (0-9).
999 = Missing. If type code (below) = V, then 999 indicates variable wind direc
* tion.
POS: 64-64
WIND-OBSERVATION direction quality code
The code that denotes a quality status of a reported WIND-OBSERVATION direction angle.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if 
* element is present
POS: 65-65
WIND-OBSERVATION type code
The code that denotes the character of the WIND-OBSERVATION.
DOM: A specific domain comprised of the characters in the ASCII character set.
A = Abridged Beaufort
B = Beaufort
C = Calm
H = 5-Minute Average Speed
N = Normal
R = 60-Minute Average Speed
Q = Squall
T = 180 Minute Average Speed
V = Variable
9 = Missing
NOTE: If a value of 9 appears with a wind speed of
*  0000, this indicates calm winds.
POS: 66-69
WIND-OBSERVATION speed rate
The rate of horizontal travel of air past a fixed point.
MIN: 0000 MAX: 0900 UNITS: meters per second
SCALING FACTOR: 10
DOM: A general domain comprised of the n

* POS: 70-70
WIND-OBSERVATION speed quality code
The code that denotes a quality status of a reported WIND-OBSERVATION speed rate.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if element is presentumeric characters (0-9).
9999 = Missing.

In [157]:
combined_df.WND.head()

8513    999,9,C,0000,1
8514    999,9,V,0021,1
8515    999,9,C,0000,1
8516    040,1,N,0026,1
8517    999,9,V,0021,1
Name: WND, dtype: object

In [158]:
combined_df[['WND_SPEED_DIR_ANGULAR', 'WND_DIR_QUALITY_CODE', 'WND_TYPE_CODE', 'WND_SPEED_MPS', 'WND_SPEED_QUALITY_CODE']] = combined_df.WND.str.split(",", expand=True)

In [159]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'WND', 'CIG', 'VIS',
       'TMP', 'DEW', 'SLP', 'GD1', 'GE1', 'GF1', 'MA1',
       'WND_SPEED_DIR_ANGULAR', 'WND_DIR_QUALITY_CODE', 'WND_TYPE_CODE',
       'WND_SPEED_MPS', 'WND_SPEED_QUALITY_CODE'],
      dtype='object')

In [69]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,WND,CIG,VIS,TMP,DEW,GD1,GE1,GF1,MA1,WND_SPEED_DIR_ANGULAR,WND_DIR_QUALITY_CODE,WND_TYPE_CODE,WND_SPEED_MPS,WND_SPEED_QUALITY_CODE
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"999,9,C,0000,1","01829,1,9,N","016093,1,9,9","+0228,1","+0156,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",999,9,C,0000,1
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"999,9,V,0021,1","22000,5,9,N","016093,1,9,9","+0211,1","+0133,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9",999,9,V,0021,1
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"999,9,C,0000,1","22000,5,9,N","016093,1,9,9","+0200,1","+0106,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9",999,9,C,0000,1
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"040,1,N,0026,1","22000,5,9,N","016093,1,9,9","+0189,1","+0100,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",040,1,N,0026,1
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"999,9,V,0021,1","02438,1,9,N","016093,1,9,9","+0178,1","+0094,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",999,9,V,0021,1

In [160]:
# Drop parent WND column
combined_df = combined_df.drop(columns=['WND'])

In [161]:
combined_df.WND_DIR_QUALITY_CODE.value_counts()

9    6594
1    4664
5    3389
Name: WND_DIR_QUALITY_CODE, dtype: int64

In [162]:
#All the value suggest Passed. column can be dropped
#1: Passed all Quality Control Checks, 
#5: Passed all Quality control checks, data originate from an NCEI data source
#9: Passed gross limits check if element is present
#Hence drop this column
combined_df.drop(columns=['WND_DIR_QUALITY_CODE'], inplace=True)

In [163]:
combined_df.WND_SPEED_QUALITY_CODE.value_counts()

1    6924
5    6873
9     850
Name: WND_SPEED_QUALITY_CODE, dtype: int64

In [164]:
#All the value suggest passed. 
#1: Passed all Quality Control Checks, 
#5: Passed all Quality control checks, data originate from an NCEI data source
#9: Passed gross limits check if element is present
#Hence drop this column, not relevant for modelling
combined_df.drop(columns=['WND_SPEED_QUALITY_CODE'], inplace=True)

In [165]:
combined_df.WND_TYPE_CODE.value_counts()

N    7427
V    4949
C    1979
9     292
Name: WND_TYPE_CODE, dtype: int64

In [166]:
#Wind Type
#A = Abridged Beaufort
#B = Beaufort
#C = Calm*
#H = 5-Minute Average Speed
#N = Normal*
#R = 60-Minute Average Speed
#Q = Squall
#T = 180 Minute Average Speed
#V = Variable*
#9 = Missing*
#Convert to category type for modelling

In [167]:
combined_df[combined_df.WND_TYPE_CODE=='9'].shape

(292, 16)

In [168]:
combined_df[(combined_df.WND_TYPE_CODE=='9') & (combined_df.WND_SPEED_MPS == '9999')].shape

(292, 16)

In [169]:
#Drop rows with WND type code == 9 as corresponding wnd speed is also not available
combined_df = combined_df[combined_df.WND_TYPE_CODE!='9']

In [170]:
#use one-hot encoding to handle categorical value
combined_df = pd.get_dummies(combined_df, columns=['WND_TYPE_CODE'], prefix='WND_TYPE_CODE')

In [171]:
combined_df.drop(columns=['WND_TYPE_CODE_C'], inplace=True)

In [172]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,CIG,VIS,TMP,DEW,SLP,GD1,GE1,GF1,MA1,WND_SPEED_DIR_ANGULAR,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"01829,1,9,N","016093,1,9,9","+0228,1","+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",999,0000,0,0
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"22000,5,9,N","016093,1,9,9","+0211,1","+0133,1","10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9",999,0021,0,1
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"22000,5,9,N","016093,1,9,9","+0200,1","+0106,1","10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9",999,0000,0,0
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"22000,5,9,N","016093,1,9,9","+0189,1","+0100,1","10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",040,0026,1,0
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"02438,1,9,N","016093,1,9,9","+0178,1","+0094,1","10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",999,0021,0,1

In [173]:
combined_df[combined_df.WND_SPEED_DIR_ANGULAR=='999'].shape[0]/combined_df.shape[0]

0.43901079763148726

In [174]:
# Drop wind angular direction column if not helping in final data-set before modelling

In [175]:
combined_df.drop(columns=['WND_SPEED_DIR_ANGULAR'], inplace=True)

##### Process CIG column
#Dropping this column as Ceiling quality of cloud doesn't interfere with the wireless signals

* POS: 71-75
SKY-CONDITION-OBSERVATION ceiling height dimension
The height above ground level (AGL) of the lowest cloud or obscuring phenomena layer aloft with 5/8 or more summation total sky cover, which may be predominantly opaque, or the vertical visibility into a surface-based obstruction. Unlimited = 22000.
MIN: 00000 MAX: 22000 UNITS: Meters
SCALING FACTOR: 1
DOM: A general domain comprised of the numeric characters (0-9).
99999 = Mis
* sing.
POS: 76-76
SKY-CONDTION-OBSERVATION ceiling quality code
The code that denotes a quality status of a reported ceiling height dimension.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if 
* element is present
POS: 77-77
SKY-CONDITION-OBSERVATION ceiling determination code
The code that denotes the method used to determine the ceiling.
DOM: A specific domain comprised of the characters in the ASCII character set.
A = Aircraft
B = Balloon
C = Statistically derived
D = Persistent cirriform ceiling (pre-1950 data)
E = Estimated
M = Measured
P = Precipitation ceiling (pre-1950 data)
R = Radar
S = ASOS augmented
U = Unknown ceiling (pre-1950 data)
V = Variable ceiling (pre-19
* 50 data)
W = Obscured
9 = Missing
POS: 78-78
SKY-CONDITION-OBSERVATION CAVOK code
The code that represents whether the 'Ceiling and Visibility Okay' (CAVOK) condition has been reported.
DOM: A specific domain comprised of the characters in the ASCII character set.
N = No
Y = Yes
9 = Missing

In [176]:
combined_df['CIG'].value_counts()

22000,5,9,N    3998
22000,1,9,N    2743
00213,1,9,N     295
00152,5,M,N     228
00274,5,M,N     207
               ...
00427,5,W,N       2
00061,5,W,N       2
00457,5,W,N       1
00396,5,W,N       1
00091,5,W,N       1
Name: CIG, Length: 137, dtype: int64

In [178]:
combined_df[['CIG_AGL', 'CIG_QC', 'CIG_METHOD', 'CIG_CAVOK']] = combined_df.CIG.str.split(",", expand=True)

In [179]:
combined_df.drop(columns=['CIG'], inplace=True)

In [180]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,VIS,TMP,DEW,SLP,GD1,GE1,GF1,MA1,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,CIG_QC,CIG_METHOD,CIG_CAVOK
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0228,1","+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",0000,0,0,01829,1,9,N
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0211,1","+0133,1","10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9",0021,0,1,22000,5,9,N
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0200,1","+0106,1","10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9",0000,0,0,22000,5,9,N
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0189,1","+0100,1","10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0026,1,0,22000,5,9,N
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0178,1","+0094,1","10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0021,0,1,02438,1,9,N

In [311]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'WND_SPEED_MPS',
       'WND_TYPE_CODE_N', 'WND_TYPE_CODE_V', 'CIG_AGL', 'CIG_QC', 'CIG_METHOD',
       'CIG_CAVOK', 'VIS_DISTANCE_MTS', 'TMP_C', 'DEW_TMP_C',
       'SLP_HECTOPASCALS', 'GD1_HEIGHT_MTS', 'GD1__1', 'GD1__2', 'GD1__3',
       'GD1__4', 'GD1__5', 'MA1_ALTIMETER_HECTOPASCAL'],
      dtype='object')

In [312]:
combined_df.CIG_AGL.value_counts()

22000    3903
213       494
183       361
244       338
152       337
         ...
1189       49
1341       44
1372       44
99999      23
30          7
Name: CIG_AGL, Length: 64, dtype: int64

In [313]:
combined_df = combined_df[combined_df.CIG_AGL != 99999]

In [314]:
combined_df.shape

(11448, 22)

In [315]:
combined_df.CIG_QC.value_counts()

1    6332
5    5116
Name: CIG_QC, dtype: int64

In [316]:
combined_df.CIG_METHOD.value_counts()

9    7492
M    3922
W      34
Name: CIG_METHOD, dtype: int64

In [317]:
combined_df.CIG_CAVOK.value_counts()

N    11448
Name: CIG_CAVOK, dtype: int64

In [318]:
combined_df = combined_df.drop(columns=['CIG_QC', 'CIG_METHOD', 'CIG_CAVOK'])

##### Process VIS column

* POS: 79-84 
VISIBILITY-OBSERVATION distance dimension
The horizontal distance at which an object can be seen and identified.
MIN: 000000 MAX: 160000 UNITS: Meters
DOM: A general domain comprised of the numeric characters (0-9).
Missing = 999999
NOTE: Values greater than 160000 are entered as 
1
* 60000
POS: 85-85
VISIBILITY-OBSERVATION distance quality code
The code that denotes a quality status of a reported distance of a visibility observation.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if
    
* element is present
POS: 86-86
VISIBILITY-OBSERVATION variability code
The code that denotes whether or not the reported visibility is variable.
DOM: A specific domain comprised of the characters in the ASCII character set.
N = Not variable
  

* V = Variable
9 = Missing
POS: 87-87
VISIBILITY-OBSERVATION quality variability code
The code that denotes a quality status of a reported VISIBILITY-OBSERVATION variability code.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if element is present

In [182]:
combined_df.VIS.value_counts()

016093,1,9,9    5465
016093,5,N,5    5101
004828,5,N,5     346
006437,5,N,5     259
004023,5,N,5     247
014484,1,9,9     234
014484,5,N,5     208
008047,5,N,5     190
012875,5,N,5     188
009656,5,N,5     176
004828,1,9,9     171
011265,5,N,5     162
008047,1,9,9     145
006437,1,9,9     145
003219,5,N,5     142
012875,1,9,9     133
002816,5,N,5     131
009656,1,9,9     130
011265,1,9,9     128
004023,1,9,9     125
003219,1,9,9      83
002414,5,N,5      63
002012,5,N,5      53
002816,1,9,9      51
001609,5,N,5      41
001207,5,N,5      41
001207,1,9,9      31
000805,5,N,5      24
002414,1,9,9      23
001609,1,9,9      21
002012,1,9,9      17
000402,5,N,5      15
000805,1,9,9      15
003219,5,V,5       9
004023,5,V,5       9
002816,5,V,5       9
999999,9,N,A       7
000402,1,9,9       6
000805,A,N,A       3
001207,5,V,5       2
000402,A,N,A       2
016093,1,N,A       1
016093,1,N,5       1
999999,9,9,9       1
002414,5,V,5       1
Name: VIS, dtype: int64

In [183]:
columns_vis = ['VIS_DISTANCE_MTS','VIS_QUALITY_CODE', 'VIS_VAR_CODE','VIS_VAR_QUALITY_CODE']
combined_df[columns_vis]= combined_df['VIS'].str.split(",", expand=True)

In [184]:
combined_df.shape

(14355, 23)

In [185]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,VIS,TMP,DEW,SLP,GD1,GE1,...,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,CIG_QC,CIG_METHOD,CIG_CAVOK,VIS_DISTANCE_MTS,VIS_QUALITY_CODE,VIS_VAR_CODE,VIS_VAR_QUALITY_CODE
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0228,1","+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999",...,0,0,01829,1,9,N,016093,1,9,9
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0211,1","+0133,1","10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999",...,0,1,22000,5,9,N,016093,1,9,9
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0200,1","+0106,1","10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999",...,0,0,22000,5,9,N,016093,1,9,9
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0189,1","+0100,1","10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999",...,1,0,22000,5,9,N,016093,1,9,9
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"016093,1,9,9","+0178,1","+0094,1","10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999",...,0,1,02438,1,9,N,016093,1,9,9

In [186]:
combined_df.VIS_VAR_CODE.value_counts()

N    7401
9    6924
V      30
Name: VIS_VAR_CODE, dtype: int64

In [187]:
combined_df.VIS_VAR_QUALITY_CODE.value_counts()

5    7418
9    6924
A      13
Name: VIS_VAR_QUALITY_CODE, dtype: int64

In [188]:
combined_df.VIS_QUALITY_CODE.value_counts()

5    7417
1    6925
9       8
A       5
Name: VIS_QUALITY_CODE, dtype: int64

In [189]:
# Drop variability observation due to missing value

In [190]:
combined_df.drop(columns=['VIS', 'VIS_VAR_CODE', 'VIS_VAR_QUALITY_CODE', 'VIS_QUALITY_CODE'], inplace=True)

In [191]:
combined_df.shape

(14355, 19)

In [192]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,TMP,DEW,SLP,GD1,GE1,GF1,MA1,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,CIG_QC,CIG_METHOD,CIG_CAVOK,VIS_DISTANCE_MTS
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"+0228,1","+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",0000,0,0,01829,1,9,N,016093
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"+0211,1","+0133,1","10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9",0021,0,1,22000,5,9,N,016093
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"+0200,1","+0106,1","10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9",0000,0,0,22000,5,9,N,016093
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"+0189,1","+0100,1","10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0026,1,0,22000,5,9,N,016093
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"+0178,1","+0094,1","10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0021,0,1,02438,1,9,N,016093

##### Process TMP
Centigrate, Quality

* POS: 88-92
AIR-TEMPERATURE-OBSERVATION air temperature
The temperature of the air.
MIN: -0932 MAX: +0618 UNITS: Degrees Celsius
SCALING FACTOR: 10
DOM: A general domain comprised of the numeric characters (0-9), a plus sign (+), and a minus sign (-).
+9999 = Mi

* POS: 93-93
AIR-TEMPERATURE-OBSERVATION air temperature quality code
The code that denotes a quality status of an AIR-TEMPERATURE-OBSERVATION.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if element is present
A = Data value flagged as suspect, but accepted as a good value
C = Temperature and dew point received from Automated Weather Observing System (AWOS) are reported in
whole degrees Celsius. Automated QC flags these values, but they are accepted as valid.
I = Data value not originally in data, but inserted by validator
M = Manual changes made to value based on information provided by NWS or FAA
P = Data value not originally flagged as suspect, but replaced by validator
R = Data value replaced with value computed by NCEI software
U = Data value replaced with edited valuessing.

In [193]:
combined_df.TMP.value_counts()

+0100,5    333
+0083,5    274
+0089,5    263
+0106,5    255
+0061,5    254
          ...
+0110,A      1
+0160,A      1
+0140,A      1
+0090,A      1
+0310,1      1
Name: TMP, Length: 211, dtype: int64

In [194]:
combined_df[['TMP_C', 'TMP_QUALITY']] = combined_df.TMP.str.split(",",expand=True)

In [195]:
combined_df.TMP_QUALITY.value_counts()

5    7419
1    6921
A       9
9       5
7       1
Name: TMP_QUALITY, dtype: int64

* 0 = Passed gross limits check* 
1 = Passed all quality control checks* 
2 = Suspec* t
3 = Erroneo* us
4 = Passed gross limits check, data originate from an NCEI data sou* rce
5 = Passed all quality control checks, data originate from an NCEI data so* urce
6 = Suspect, data originate from an NCEI data s* ource
7 = Erroneous, data originate from an NCEI data * source
9 = Passed gross limits check if element is * present
A = Data value flagged as suspect, but accepted as a good value

In [196]:
combined_df = combined_df[combined_df.TMP_QUALITY!='7']

In [197]:
combined_df.shape

(14354, 21)

In [198]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,TMP,DEW,SLP,GD1,GE1,GF1,...,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,CIG_QC,CIG_METHOD,CIG_CAVOK,VIS_DISTANCE_MTS,TMP_C,TMP_QUALITY
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"+0228,1","+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9",...,0000,0,0,01829,1,9,N,016093,+0228,1
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"+0211,1","+0133,1","10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9",...,0021,0,1,22000,5,9,N,016093,+0211,1
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"+0200,1","+0106,1","10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9",...,0000,0,0,22000,5,9,N,016093,+0200,1
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"+0189,1","+0100,1","10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9",...,0026,1,0,22000,5,9,N,016093,+0189,1
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"+0178,1","+0094,1","10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9",...,0021,0,1,02438,1,9,N,016093,+0178,1

In [199]:
combined_df.drop(columns=['TMP'], inplace=True)

C:\Users\ukhan\AppData\Local\Temp\ipykernel_37636\3078245836.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df.drop(columns=['TMP'], inplace=True)

In [200]:
combined_df = combined_df.drop(columns=['TMP_QUALITY'])

In [201]:
combined_df.shape

(14354, 19)

In [202]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,DEW,SLP,GD1,GE1,GF1,MA1,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,CIG_QC,CIG_METHOD,CIG_CAVOK,VIS_DISTANCE_MTS,TMP_C
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"+0156,1","10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",0000,0,0,01829,1,9,N,016093,+0228
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"+0133,1","10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9",0021,0,1,22000,5,9,N,016093,+0211
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"+0106,1","10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9",0000,0,0,22000,5,9,N,016093,+0200
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"+0100,1","10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0026,1,0,22000,5,9,N,016093,+0189
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"+0094,1","10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0021,0,1,02438,1,9,N,016093,+0178

In [203]:
combined_df.TMP_C.value_counts()

+0100    534
+0083    480
+0089    462
+0067    454
+0061    452
        ...
+0339      4
+0280      3
+0344      1
+0310      1
-0083      1
Name: TMP_C, Length: 107, dtype: int64

In [204]:
combined_df.TMP_C = combined_df.TMP_C.astype(int)

In [205]:
combined_df.TMP_C.info()

<class 'pandas.core.series.Series'>
Int64Index: 14354 entries, 8513 to 38210
Series name: TMP_C
Non-Null Count  Dtype
--------------  -----
14354 non-null  int32
dtypes: int32(1)
memory usage: 168.2 KB

In [206]:
combined_df.TMP_C.describe()

count    14354.000000
mean       108.478821
std        199.264306
min        -83.000000
25%         56.000000
50%         94.000000
75%        150.000000
max       9999.000000
Name: TMP_C, dtype: float64

In [207]:
combined_df = combined_df[combined_df['TMP_C']!=9999]

In [208]:
combined_df.shape

(14349, 19)

#### Process DEW

* POS: 94-98
AIR-TEMPERATURE-OBSERVATION dew point temperature
The temperature to which a given parcel of air must be cooled at constant pressure and water vapor
content in order for saturation to occur.
MIN: -0982 MAX: +0368 UNITS: Degrees Celsius
SCALING FACTOR: 10
DOM: A general domain comprised of the numeric characters (0-9), a plus sign (+), and a minus sin (-).
+Missingi

* ssing.
POS: 99-99
AIR-TEMPERATURE-OBSERVATION dew point quality code
The code that denotes a quality status of the reported dew point temperature.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if element is present
A = Data value flagged as suspect, but accepted as a good value
C = Temperature and dew point received from Automated Weather Observing System (AWOS) are reported in
whole degrees Celsius. Automated QC flags these values, but they are accepted as valid.
I = Data value not originally in data, but inserted by validator
M = Manual changes made to value based on information provided by NWS or FAA
P = Data value not originally flagged as suspect, but replaced by validator
R = Data value replaced with value computed by NCEI software
U = Data value replaced with edited value

In [209]:
combined_df.DEW.value_counts()

+0050,1    219
+0067,5    206
+0061,5    191
-0006,5    186
+0078,5    186
          ...
-0070,1      1
+0233,1      1
-0090,5      1
-0194,5      1
+0170,5      1
Name: DEW, Length: 201, dtype: int64

In [210]:
combined_df[['DEW_TMP_C', 'DEW_QUALITY_CODE']] = combined_df.DEW.str.split(",", expand=True)

In [211]:
combined_df.shape

(14349, 21)

In [212]:
combined_df.DEW_QUALITY_CODE.value_counts()

5    7383
1    6921
9      36
A       9
Name: DEW_QUALITY_CODE, dtype: int64

0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if element is present
A = Data value flagged as suspect, but accepted as a good value

In [213]:
#Quality is satisfactory, no processing required hence dropping the columns
combined_df = combined_df.drop(columns=['DEW', 'DEW_QUALITY_CODE'])

In [214]:
combined_df.shape

(14349, 19)

In [215]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,SLP,GD1,GE1,GF1,MA1,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,CIG_QC,CIG_METHOD,CIG_CAVOK,VIS_DISTANCE_MTS,TMP_C,DEW_TMP_C
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"10176,1","4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",0000,0,0,01829,1,9,N,016093,228,+0156
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"10183,1","1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9",0021,0,1,22000,5,9,N,016093,211,+0133
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"10188,1","1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9",0000,0,0,22000,5,9,N,016093,200,+0106
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"10190,1","1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0026,1,0,22000,5,9,N,016093,189,+0100
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"10191,1","3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0021,0,1,02438,1,9,N,016093,178,+0094

In [216]:
combined_df.DEW_TMP_C = combined_df.DEW_TMP_C.astype(int)

In [217]:
combined_df.DEW_TMP_C.describe()

count    14349.000000
mean        64.310823
std        505.108228
min       -194.000000
25%        -22.000000
50%         44.000000
75%        100.000000
max       9999.000000
Name: DEW_TMP_C, dtype: float64

In [223]:
combined_df = combined_df[combined_df.DEW_TMP_C != 9999]

In [224]:
combined_df.shape

(14313, 19)

#### Process SLP (Sea Level Pressure)

* POS: 100-104
ATMOSPHERIC-PRESSURE-OBSERVATION sea level pressure
The air pressure relative to Mean Sea Level (MSL).
MIN: 08600 MAX: 10900 UNITS: Hectopascals
SCALING FACTOR: 10
DOM: A general domain comprised of the numeric characters (0-9).
99999 = Mis
* sing.
POS: 105-105
ATMOSPHERIC-PRESSURE-OBSERVATION sea level pressure quality code
The code that denotes a quality status of the sea level pressure of an
ATMOSPHERIC-PRESSURE-OBSERVATION.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Passed gross limits check if element is present

In [225]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'SLP', 'GD1', 'GE1',
       'GF1', 'MA1', 'WND_SPEED_MPS', 'WND_TYPE_CODE_N', 'WND_TYPE_CODE_V',
       'CIG_AGL', 'CIG_QC', 'CIG_METHOD', 'CIG_CAVOK', 'VIS_DISTANCE_MTS',
       'TMP_C', 'DEW_TMP_C'],
      dtype='object')

In [227]:
combined_df.SLP.value_counts()

99999,9    2830
10161,5      46
10163,5      43
10168,1      42
10164,1      41
           ...
09988,1       1
09862,5       1
09874,5       1
09876,5       1
09989,5       1
Name: SLP, Length: 938, dtype: int64

In [231]:
combined_df[['SLP_HECTOPASCALS','SLP_QUALITY_CODE']] = combined_df.SLP.str.split(',', expand=True)

In [232]:
new_combined_df.SLP_QUALITY_CODE.value_counts()

5    5781
1    5689
9    2830
2       7
6       6
Name: SLP_QUALITY_CODE, dtype: int64

In [233]:
combined_df = combined_df[(combined_df.SLP_QUALITY_CODE!='2') & (combined_df.SLP_QUALITY_CODE!='6')]

In [234]:
combined_df.shape

(14300, 21)

In [235]:
combined_df = combined_df.drop(columns=['SLP', 'SLP_QUALITY_CODE'])

In [236]:
combined_df.shape

(14300, 19)

In [237]:
combined_df.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,GD1,GE1,GF1,MA1,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,CIG_QC,CIG_METHOD,CIG_CAVOK,VIS_DISTANCE_MTS,TMP_C,DEW_TMP_C,SLP_HECTOPASCALS
8513,2023-10-29 00:56:00,40.701214,-74.009028,2.13,"4,99,1,+01829,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,01829,1,99,9,99,9","10176,1,99999,9",0000,0,0,01829,1,9,N,016093,228,156,10176
8514,2023-10-29 01:56:00,40.701214,-74.009028,2.13,"1,99,1,+01981,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01981,1,99,9,99,9","10186,1,99999,9",0021,0,1,22000,5,9,N,016093,211,133,10183
8515,2023-10-29 02:56:00,40.701214,-74.009028,2.13,"1,99,1,+01829,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,01829,1,99,9,99,9","10190,1,99999,9",0000,0,0,22000,5,9,N,016093,200,106,10188
8516,2023-10-29 03:56:00,40.701214,-74.009028,2.13,"1,99,1,+02438,1,9","9,AGL ,+99999,+99999","02,99,5,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0026,1,0,22000,5,9,N,016093,189,100,10190
8517,2023-10-29 04:56:00,40.701214,-74.009028,2.13,"3,99,1,+02438,1,9","9,AGL ,+99999,+99999","99,99,9,99,9,99,9,02438,1,99,9,99,9","10193,1,99999,9",0021,0,1,02438,1,9,N,016093,178,94,10191

#### Process GD1

FLD LEN: 3
SKY-COVER-SUMMATION-STATE identifier
The identifier that denotes the availability of a SKY-COVER-SUMMATION-STATE.
DOM: A specific domain comprised of the ASCII characters.
GD1 - GD6 An indicator of up to 6 repeating fields of the following items:
SKY-COVER-SUMMATION-STATE coverage code
SKY-COVER-SUMMATION-STATE coverage code #2
SKY-COVER-SUMMATION-STATE coverage quality code
SKY-COVER-SUMMATION-STATE height dimension
SKY-COVER-SUMMATION-STATE height dimension quality code
SKY-COVER-SUMMATION-STATE characteri* stic code
FLD LEN: 1
SKY-COVER-SUMMATION-STATE coverage code
The code that denotes the portion of the total celestial dome covered by all layers of clouds and other
obscuring phenomena at or below a given height.
DOM: A specific domain comprised of the ASCII characters
0 = Clear - No coverage
1 = FEW - 2/8 or less coverage (no
2 = SCATTERED - 3/8-4/8 coverage
3 = BROKEN - 5/8-7/8 coverage
4 = OVERCAST - 8/8 coverage
5 = OBSCURED
6 = PARTIALLY OBSCURED
9 = MIS* SING
FLD LEN: 2
SKY-COVER-SUMMATION coverage code #2
The code that denotes the fraction of the total celestial dome covered by a by all layers of clouds and other
obscuring phenomena at or below a given height, if reported by the station in octas.
DOM: A specific domain comprised of the characters in the ASCII character set.
00 = None, SKC or CLR
01 = One okta - 1/10 or less but not zero
02 = Two oktas - 2/10 - 3/10, or FEW
03 = Three oktas - 4/10
04 = Four oktas - 5/10, or SCT
05 = Five oktas - 6/10
06 = Six oktas - 7/10 - 8/10
07 = Seven oktas - 9/10 or more but not 10/10, or BKN
08 = Eight oktas - 10/10, or OVC
09 = Sky obscured, or cloud amount cannot be estimated
10 = Partial Obscuration
11 = Thin Scattered
12 = Scattered
13 = Dark Scattered
14 = Thin Broken
15 = Broken
16 = Dark Broken
17 = Thin Overcast
18 = Overcast
19*  = Dark overcast
99 = Missing
FLD LEN: 1
SKY-COVER-SUMMATION-STATE coverage quality code
The code that denotes a quality status of the reported SKY-COVER-SUMMATION-STATE coverage.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
9 = Pass* ed gross limits check if element is present
FLD LEN: 6
SKY-COVER-SUMMATION-STATE height dimension
The height above ground level (AGL) of the base of the cloud layer or obscuring phenomena.
MIN: -00400 MAX: +35000 UNITS: meters
SCALING FACTOR: 1
DOM: A general domain compirsed of the ASCII characters 0-9, * a plus (+) and a minus sign (-).
+99999 = Missing
FLD LEN: 1
SKY-COVER-SUMMATION-STATE height dimension quality code
The code that denotes a quality status of the reported SKY-COVER-SUMMATION-STATE height dimension.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits checkchec, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI d* FLD LEN: 1
SKY-COVER-SUMMATION-STATE characteristic code
The code that represents a characteristic of a specific cloud or other obscuring phenomena layer.
DOM: A specific domain comprised of the characters in the ASCII character set.
1 = Variable height
2 = Variable amount
3 = Thin clouds
4 = Dark layer (reported in data prior to 1950)
9 = Missingata source
9 = Passed gross limits check if element is present
t including zero)

In [239]:
combined_df.GD1.value_counts()

0,99,1,+99999,9,9    2829
4,99,1,+00152,5,9     208
4,99,1,+00213,1,9     172
4,99,1,+00122,5,9     164
4,99,1,+00183,5,9     162
                     ...
2,99,1,+00213,1,1       1
2,99,1,+02591,9,9       1
2,99,1,+00945,1,9       1
1,99,1,+01433,1,9       1
4,99,1,+00091,5,1       1
Name: GD1, Length: 540, dtype: int64

In [240]:
combined_df[['GD1_COV_CODE','GD1_COV_CODE2', 'GD1_QC', 'GD1_HEIGHT_MTS', 'GD1_HT_QC', 'GD1_CHAR_CODE']] = combined_df.GD1.str.split(',', expand=True)

In [241]:
combined_df.GD1_COV_CODE.value_counts()

4    4011
0    2829
3    2047
1    1359
2    1265
5      34
Name: GD1_COV_CODE, dtype: int64

In [272]:
combined_df = pd.get_dummies(combined_df, columns=['GD1_COV_CODE'], drop_first=True, prefix='GD1_')

In [273]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'MA1', 'WND_SPEED_MPS',
       'WND_TYPE_CODE_N', 'WND_TYPE_CODE_V', 'CIG_AGL', 'CIG_QC', 'CIG_METHOD',
       'CIG_CAVOK', 'VIS_DISTANCE_MTS', 'TMP_C', 'DEW_TMP_C',
       'SLP_HECTOPASCALS', 'GD1_HEIGHT_MTS', 'GD1__1', 'GD1__2', 'GD1__3',
       'GD1__4', 'GD1__5'],
      dtype='object')

In [274]:
combined_df.shape

(14300, 22)

In [242]:
combined_df.GD1_COV_CODE2.value_counts()

99    11545
Name: GD1_COV_CODE2, dtype: int64

In [243]:
combined_df = combined_df.drop(columns=['GD1_COV_CODE2'])

In [244]:
combined_df.GD1_QC.value_counts()

1    11545
Name: GD1_QC, dtype: int64

In [245]:
combined_df = combined_df.drop(columns=['GD1_QC'])

In [246]:
combined_df.GD1_HEIGHT_MTS.value_counts()

+99999    2829
+00213     513
+00244     453
+00274     429
+00183     390
          ...
+01372      55
+00945      54
+00975      53
+01341      44
+00030      15
Name: GD1_HEIGHT_MTS, Length: 63, dtype: int64

In [276]:
combined_df = combined_df[combined_df.GD1_HEIGHT_MTS != "+99999"]

In [277]:
combined_df.shape

(11471, 22)

In [247]:
combined_df.GD1_HT_QC.value_counts()

5    4546
1    3922
9    3077
Name: GD1_HT_QC, dtype: int64

In [248]:
# passed all criteria
combined_df = combined_df.drop(columns=['GD1_HT_QC'])

In [254]:
combined_df.GD1_CHAR_CODE.value_counts()

9    11049
1      496
Name: GD1_CHAR_CODE, dtype: int64

In [255]:
# passed all criteria
combined_df = combined_df.drop(columns=['GD1_CHAR_CODE'])

In [251]:
# passed all criteria
combined_df = combined_df.drop(columns=['GD1'])

In [256]:
combined_df.shape

(14300, 20)

In [257]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'GE1', 'GF1', 'MA1',
       'WND_SPEED_MPS', 'WND_TYPE_CODE_N', 'WND_TYPE_CODE_V', 'CIG_AGL',
       'CIG_QC', 'CIG_METHOD', 'CIG_CAVOK', 'VIS_DISTANCE_MTS', 'TMP_C',
       'DEW_TMP_C', 'SLP_HECTOPASCALS', 'GD1_COV_CODE', 'GD1_HEIGHT_MTS'],
      dtype='object')

#### Process GE1

FLD LEN: 3
SKY-CONDITION-OBSERVATION identifier
An indicator that denotes the start of a SKY-CONDITION-OBSERVATION data group.
DOM: A specific domain comprised of the characters in the ASCII character set.
GE1: An indicator of the occurrence of the following data items:
SKY-CONDITION-OBSERVATION convective cloud attribute
SKY-CONDITION-OBSERVATION vertical datum attribute
SKY-CONDITION-OBSERVATION base height upper range attribute
SKY-CONDITION-OBSERVATION base height lower range attribute
FLD LEN: 1
SKY-CONDITION-OBSERVATION convective cloud attribute
The code that denotes the convective cloud type in an observation.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = None
1 = ACSL (Altocumulus Standing Lenticular)
2 = ACCAS (Altocumulus Castelanus)
3 = TCU (Towering Cumulus)
4 = MDT CU (Moderate Cumulus)
5 = CB/CB MAM DISTANT (Cumulonimbus or Cumulonimbus Mammatus in the distance)
6 = CB/CBMAM (Cumulonimbus or Cumulonimbus Mammatus within 20 nautical miles)
7 = Unknown
9 = missing
FLD LEN: 6
SKY-CONDITION-OBSERVATION vertical datum attribute
The code that represents a VERTICAL-REFERENCE-DATUM. Under the stewardship of the FDAD for Intelligence.
DOM: A specific domain comprised of the characters in the ASCII character set.
AGL: Above Ground Level
ALAT: Approximate lowest astronomical tide
AP: Apparent
CFB: Crest of first berm
CRD: Columbia River datum
ESLW: Equatorial Spring low water
GCLWD: Gulf Coast low water datum
HAT: Highest astronomical tide
HHW: Higher high water
HTWW: High tide wave wash
HW: High water
HWFC: High water full and change
IND: Indefinite
ISLW: Indian Spring low water
LAT: Lowest astronomical tide
LLW: Lowest low water
LNLW: Lowest normal low water
LRLW: Lower low water
LSD: Land survey datum
LW: Low water
LWD: Low water datum
LWFC: Low water full and charge
MHHW: Mean higher high water
MHLW: Mean higher low water
MHW: Mean high water
MHWN: Mean high water neap
MHWS: Mean high water spring
MLHW: Mean lower high water
MLLW: Me
MLWN: Mean low water neap
MLW: Mean low water
MLWS: Mean low water spring
MSL: Mean sea level
MTL: Mean tide level
NC: No correction
NT: Neap tide
ST: Spring tide
SWA: Storm wave action
TLLW: Tropic lower low water
UD: Undetermined
UK: Unknown
WGS84E: WGS84 Ellispoid
WGS84G: WGS84 GEOID
999999: missing
FLD LEN: 6
SKY-CONDITION-OBSERVATION base height upper range attribute
The height relative to a VERTICAL-REFERENCE-DATUM for cloud bases reported in a range or the highest theight for a variable cloud height report. The concept of a range is to accommodate the WMO practice of reporting a cloud layer by a range of heights.
MIN: -0400 MAX: +15000 UNITS: meters
DOM: A general domain compirsed of the ASCII characters 0-9, a plus (+) and a minus sign (-).
+99999 = Missing
FLD LEN: 6
SKY-CONDITION-OBSERVATION base height lower range attribute
The height relative to a VERTICAL-REFERENCE-DATUM for cloud bases reported in a range or lowest height for a variable cloud height report. The concept of a range is to accommodate the WMO ractice of reporting a cloud layer by arange of heights.
MIN: -0400 MAX: +15000 UNITS: meters
DOM: A general domain compirsed of the ASCII characters 0-9, a plus (+) and a minus si▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀an lower low water
MLLWS: Mean lower low water springs

In [259]:
combined_df.shape

(14300, 20)

In [261]:
combined_df.GE1.value_counts()

9,AGL   ,+99999,+99999    8356
Name: GE1, dtype: int64

In [262]:
# dropping GE1 as sky condition information is missing
combined_df = combined_df.drop(columns=['GE1'])

In [263]:
combined_df.shape

(14300, 19)

##### process GF1

In [264]:
combined_df.GF1.value_counts()

00,99,1,99,9,99,9,99999,9,99,9,99,9    5496
99,99,9,99,9,99,9,00213,1,99,9,99,9     480
99,99,9,99,9,99,9,00244,1,99,9,99,9     414
99,99,9,99,9,99,9,00274,1,99,9,99,9     396
99,99,9,99,9,99,9,00183,1,99,9,99,9     358
                                       ...
02,99,5,99,9,99,9,00853,1,99,9,99,9       1
02,99,5,99,9,99,9,00122,1,99,9,99,9       1
09,99,1,99,9,99,9,00091,1,99,9,99,9       1
04,99,5,99,9,99,9,00914,1,99,9,99,9       1
04,99,5,99,9,99,9,01006,1,99,9,99,9       1
Name: GF1, Length: 193, dtype: int64

In [265]:
# most of the cloud coverage data is unavailable, cloud base height dimenstion is available from GD1 data.
# Hence dropping this information

In [266]:
combined_df = combined_df.drop(columns=['GF1'])

In [267]:
combined_df.shape

(14300, 18)

In [268]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'MA1', 'WND_SPEED_MPS',
       'WND_TYPE_CODE_N', 'WND_TYPE_CODE_V', 'CIG_AGL', 'CIG_QC', 'CIG_METHOD',
       'CIG_CAVOK', 'VIS_DISTANCE_MTS', 'TMP_C', 'DEW_TMP_C',
       'SLP_HECTOPASCALS', 'GD1_COV_CODE', 'GD1_HEIGHT_MTS'],
      dtype='object')

##### Process MA1

Pressure Data
FLD LEN: 3
ATMOSPHERIC-PRESSURE-OBSERVATION identifier
The identifier that denotes the start of an ATMOSPHERIC-PRESSURE-OBSERVATION data section.
DOM: A specific domain comprised of the characters in the ASCII character set.
MA1An indicator of the occurrence of the following items:
ATMOSPHERIC-PRESSURE-OBSERVATION altimeter setting rate
ATMOSPHERIC-PRESSURE-OBSERVATION altimeter quality code
ATMOSPHERIC-PRESSURE-OBSERVATION station pressure rate
ATMOSPHERIC-PRESSURE-OBSERVATION station pressure quality code
FLD LEN: 5
ATMOSPHERIC-PRESSURE-OBSERVATION altimeter setting rate
The pressure value to which an aircraft altimeter is set so that it will indicate the altitude relative to mean sea level of an aircraft on the ground at the location for which the value was determined.
MIN: 08635 MAX: 10904 UNITS: Hectopascals
SCALING FACTOR: 10
DOM: A general domain comprised of the numeric characters (0-9).
FLD LEN: 1
ATMOSPHERIC-PRESSURE-OBSERVATION altimeter quality code
The code that denotes a quality status of an altimeter setting rate.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
M = Manual change made to value based on information provided by NWS or FAA
9 = Passed gross limits check if element is present
FLD LEN: 5
ATMOSPHERIC-PRESSURE-OBSERVATION station pressure rate
The atmospheric pressure at the observation point.
MIN: 04500 MAX: 10900 UNITS: Hectopascals
SCALING FACTOR: 10
DOM: A general domain comprised of the numeric characters (0-9).
99999 = Missing.
FLD LEN: 1
ATMOSPHERIC-PRESSURE-OBSERVATION station pressure quality code
The code that denotes a quality status of the station pressure of an ATMOSPHERIC-PRESSURE-OBSERVATION.
DOM: A specific domain comprised of the characters in the ASCII character set.
0 = Passed gross limits check
1 = Passed all quality control checks
2 = Suspect
3 = Erroneous
4 = Passed gross limits check, data originate from an NCEI data source
5 = Passed all quality control checks, data originate from an NCEI data source
6 = Suspect, data originate from an NCEI data source
7 = Erroneous, data originate from an NCEI data source
M = Manual change made to value based on information provided by NWS or FAA
9 = Passed gross limits check if element is present
Missing = 99999

In [278]:
combined_df.MA1.value_counts()

10176,1,99999,9    146
10173,1,99999,9    139
10169,1,99999,9    137
10163,1,99999,9    135
10166,1,99999,9    130
                  ...
09837,5,09781,5      1
09834,5,09778,5      1
09831,6,09775,6      1
09837,6,09781,6      1
09827,6,09771,6      1
Name: MA1, Length: 328, dtype: int64

In [279]:
combined_df[['MA1_ALTIMETER_HECTOPASCAL', 'MA1_QC', 'MA1_STATION_PRES_HECT', 'MA1_STATION_PRESSURE_QC']] = combined_df.MA1.str.split(",", expand=True)

C:\Users\ukhan\AppData\Local\Temp\ipykernel_37636\2749325446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df[['MA1_ALTIMETER_HECTOPASCAL', 'MA1_QC', 'MA1_STATION_PRES_HECT', 'MA1_STATION_PRESSURE_QC']] = combined_df.MA1.str.split(",", expand=True)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_37636\2749325446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df[['MA1_ALTIMETER_HECTOPASCAL', 'MA1_QC', 'MA1_STATION_PRES_HECT', 'MA1_STATION_PRESSURE_QC']] = combined_df.MA1.str.split(",", expand=True)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_37636\2749325446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df[['MA1_ALTIMETER_HECTOPASCAL', 'MA1_QC', 'MA1_STATION_PRES_HECT', 'MA1_STATION_PRESSURE_QC']] = combined_df.MA1.str.split(",", expand=True)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_37636\2749325446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df[['MA1_ALTIMETER_HECTOPASCAL', 'MA1_QC', 'MA1_STATION_PRES_HECT', 'MA1_STATION_PRESSURE_QC']] = combined_df.MA1.str.split(",", expand=True)

In [281]:
combined_df = combined_df.drop(columns=['MA1'])

In [282]:
combined_df.MA1_ALTIMETER_HECTOPASCAL.value_counts()

10176    229
10169    224
10159    216
10163    214
10173    204
        ...
09881      1
09858      1
09834      1
09827      1
09926      1
Name: MA1_ALTIMETER_HECTOPASCAL, Length: 175, dtype: int64

In [302]:
combined_df.MA1_QC.value_counts()

1    6908
5    4541
2       7
6       7
9       1
Name: MA1_QC, dtype: int64

In [303]:
combined_df = combined_df.drop(columns=['MA1_QC'])

In [300]:
combined_df.MA1_STATION_PRES_HECT.value_counts()

99999    6916
10101      96
10125      93
10098      89
10112      86
         ...
09801       1
09869       1
09812       1
09778       1
09825       1
Name: MA1_STATION_PRES_HECT, Length: 157, dtype: int64

In [301]:
combined_df = combined_df.drop(columns=['MA1_STATION_PRES_HECT', 'MA1_STATION_PRESSURE_QC'])

In [319]:
combined_df.shape

(11448, 19)

In [320]:
combined_df.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'WND_SPEED_MPS',
       'WND_TYPE_CODE_N', 'WND_TYPE_CODE_V', 'CIG_AGL', 'VIS_DISTANCE_MTS',
       'TMP_C', 'DEW_TMP_C', 'SLP_HECTOPASCALS', 'GD1_HEIGHT_MTS', 'GD1__1',
       'GD1__2', 'GD1__3', 'GD1__4', 'GD1__5', 'MA1_ALTIMETER_HECTOPASCAL'],
      dtype='object')

In [238]:
combined_df.to_csv(csv_files_path+'2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_chkpoint2.csv', index=False)

In [321]:
combined_df.to_csv(csv_files_path+'2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_chkpoint2_22cols.csv', index=False)

## Checkpoint#2: Processed weather data

In [189]:
combined_df = pd.read_csv(csv_files_path+'2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_chkpoint2.csv')

In [322]:
combined_df = pd.read_csv(csv_files_path+'2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_chkpoint2_22cols.csv')

In [323]:
combined_df.shape

(11448, 19)

In [324]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11448 entries, 0 to 11447
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   DATE                       11448 non-null  object
 1   LATITUDE                   11448 non-null  float64
 2   LONGITUDE                  11448 non-null  float64
 3   ELEVATION                  11448 non-null  float64
 4   WND_SPEED_MPS              11448 non-null  int64
 5   WND_TYPE_CODE_N            11448 non-null  int64
 6   WND_TYPE_CODE_V            11448 non-null  int64
 7   CIG_AGL                    11448 non-null  int64
 8   VIS_DISTANCE_MTS           11448 non-null  int64
 9   TMP_C                      11448 non-null  int64
 10  DEW_TMP_C                  11448 non-null  int64
 11  SLP_HECTOPASCALS           11448 non-null  int64
 12  GD1_HEIGHT_MTS             8705 non-null   float64
 13  GD1__1                     11448 non-null  int64
 14  GD1__2                     11448 non-null  int64
 15  GD1__3                     11448 non-null  int64
 16  GD1__4                     11448 non-null  int64
 17  GD1__5                     11448 non-null  int64
 18  MA1_ALTIMETER_HECTOPASCAL  11448 non-null  float64
dtypes: float64(5), int64(13), object(1)
memory usage: 1.7+ MB

In [325]:
combined_df[['LATITUDE','LONGITUDE']].value_counts()

LATITUDE   LONGITUDE
40.701214  -74.009028    6878
40.778980  -73.969250    4570
dtype: int64