In [1]:
import pandas as pd
import glob
import os

In [2]:
# Define the path to your directory containing Excel files
# You can use a wildcard '*' to match all Excel files (.xlsx or .xls): 
# 
open_mesh_path = "C:/Users/ukhan/Documents/DataSet/OpenMesh/"

In [3]:
link_metadata_df = pd.read_csv(open_mesh_path + "links_metadata.csv")
link_rawdata_df = pd.read_csv(open_mesh_path + "links_rawdata.csv")

## 1. Process link_metadata

In [4]:
link_metadata_df.shape, link_rawdata_df.shape

((103, 9), (354241, 104))

In [11]:
link_metadata_df[['site_0_lat', 'site_0_lon', 'length']].value_counts()

site_0_lat  site_0_lon  length
40.686020   -73.917496  1283.1    4
40.716098   -73.985997  1051.4    3
40.606661   -73.992934  865.6     2
40.658028   -74.004772  2171.1    2
40.815434   -73.950275  1834.8    2
                                 ..
40.696052   -73.939780  1147.5    1
40.696093   -73.939749  2178.1    1
40.708452   -73.921893  809.1     1
40.710900   -74.001200  570.4     1
40.696038   -73.939764  784.2     1
Length: 83, dtype: int64

In [12]:
link_metadata_df[['site_0_lat', 'site_0_lon']].value_counts()

site_0_lat  site_0_lon
40.686020   -73.917496    4
40.686016   -73.917493    3
40.645933   -74.013631    3
40.729552   -73.945949    3
40.727553   -73.946045    3
                         ..
40.710900   -74.001200    1
40.711085   -74.001295    1
40.711087   -74.001302    1
40.711109   -74.001289    1
40.696038   -73.939764    1
Length: 68, dtype: int64

In [10]:
link_metadata_df['length'].value_counts()

1283.1    4
1051.4    3
623.0     2
3489.4    2
24.5      2
         ..
2373.7    1
570.4     1
1147.5    1
2216.4    1
4505.6    1
Name: length, Length: 78, dtype: int64

In [6]:
((link_metadata_df['site_0_lat']>40.5) & (link_metadata_df['site_0_lat']<40.9)).sum()

103

In [7]:
((link_metadata_df['site_0_lon']<-73.9) & (link_metadata_df['site_0_lon']>-74.1)).sum()

103

In [8]:
link_metadata_df.isna().sum()

sublink_id      0
frequency       0
length          0
site_0_lat      0
site_0_lon      0
site_1_lat      0
site_1_lon      0
rsl             0
polarization    0
dtype: int64

In [9]:
link_metadata_df.head()

,sublink_id,frequency,length,site_0_lat,site_0_lon,site_1_lat,site_1_lon,rsl,polarization
0,1,62640,623.0,40.729552,-73.945949,40.733910,-73.950594,-60.0,Vertical
1,2,60480,222.1,40.727553,-73.946045,40.729552,-73.945949,-62.0,Vertical
2,3,62640,623.0,40.729552,-73.945949,40.733910,-73.950594,-60.0,Vertical
3,4,58320,451.8,40.736760,-73.954410,40.733902,-73.950604,-57.0,Vertical
4,5,60480,222.1,40.729552,-73.945949,40.727553,-73.946045,-57.0,Vertical

In [13]:
link_metadata_df[link_metadata_df['frequency']==68040]

,sublink_id,frequency,length,site_0_lat,site_0_lon,site_1_lat,site_1_lon,rsl,polarization
6,7,68040,3486.6,40.715587,-73.984400,40.727403,-73.946167,-58.0,Vertical
7,8,68040,2178.1,40.696093,-73.939749,40.686198,-73.917500,-50.0,Vertical
15,16,68040,631.4,40.672601,-73.964191,40.678131,-73.962457,-52.0,Vertical
23,24,68040,2791.9,40.715587,-73.984400,40.725693,-73.954143,-55.0,Vertical
26,27,68040,1355.5,40.672554,-73.964452,40.660742,-73.960408,-64.0,Vertical
31,32,68040,839.7,40.672599,-73.964204,40.680123,-73.963210,-62.0,Vertical
35,36,68040,839.7,40.672599,-73.964204,40.680123,-73.963210,-62.0,Vertical
36,37,68040,4316.1,40.635115,-73.950557,40.672517,-73.964437,-58.0,Vertical
39,40,68040,1987.9,40.672556,-73.964435,40.655626,-73.956798,-60.0,Vertical
43,44,68040,101.5,40.672601,-73.964193,40.673511,-73.964084,-60.0,Vertical
47,48,68040,2183.0,40.686139,-73.917512,40.696096,-73.939780,-47.0,Vertical
49,50,68040,2392.7,40.674458,-73.940297,40.696002,-73.939870,-53.0,Vertical
64,65,68040,2373.7,40.695814,-73.939695,40.674444,-73.940320,-63.0,Vertical

In [14]:
link_metadata_df['frequency'].value_counts()

68040    13
5490      8
5560      8
64800     7
5710      7
58320     6
60480     5
5760      4
24200     4
62640     4
24100     4
65880     3
5510      3
5810      3
5310      3
5570      2
5300      2
69120     2
5770      2
5795      2
5740      1
5500      1
5815      1
5270      1
5550      1
5280      1
5495      1
5750      1
5825      1
5505      1
5700      1
Name: frequency, dtype: int64

In [15]:
link_metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sublink_id    103 non-null    int64
 1   frequency     103 non-null    int64
 2   length        103 non-null    float64
 3   site_0_lat    103 non-null    float64
 4   site_0_lon    103 non-null    float64
 5   site_1_lat    103 non-null    float64
 6   site_1_lon    103 non-null    float64
 7   rsl           103 non-null    float64
 8   polarization  103 non-null    object
dtypes: float64(6), int64(2), object(1)
memory usage: 7.4+ KB

## 2. Process Raw Data

In [16]:
link_rawdata_df.shape

(354241, 104)

In [17]:
link_rawdata_df.head()

,Datetime,1,2,3,4,5,6,7,8,9,...,94,95,96,97,98,99,100,101,102,103
0,2023-10-29 00:00:00,-65.0,-62.0,-61.0,-54.0,-60.0,-49.0,-58.0,-49.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-10-29 00:01:00,-65.0,-61.0,-61.0,-55.0,-56.0,-49.0,-58.0,-49.0,-83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-10-29 00:02:00,-65.0,-61.0,-60.0,-55.0,-58.0,-49.0,-58.0,-50.0,-83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-10-29 00:03:00,-65.0,-62.0,-61.0,-55.0,-56.0,-51.0,-58.0,-49.0,-83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-10-29 00:04:00,-65.0,-62.0,-62.0,-56.0,-57.0,-50.0,-58.0,-49.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
link_rawdata_df.isna().sum()

Datetime        0
1           24092
2           14227
3           21062
4           20929
            ...
99          37255
100         43406
101         33941
102         44075
103         32976
Length: 104, dtype: int64

In [19]:
link_rawdata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354241 entries, 0 to 354240
Columns: 104 entries, Datetime to 103
dtypes: float64(103), object(1)
memory usage: 281.1+ MB

##### Melt the link_rawdata_df to long format

In [20]:
link_rawdata_melted = link_rawdata_df.melt(id_vars=['Datetime'], var_name='sublink_id', value_name='rsl_value')

In [21]:
link_rawdata_melted.shape

(36486823, 3)

In [22]:
link_rawdata_melted.head()

              Datetime sublink_id  rsl_value
0  2023-10-29 00:00:00          1      -65.0
1  2023-10-29 00:01:00          1      -65.0
2  2023-10-29 00:02:00          1      -65.0
3  2023-10-29 00:03:00          1      -65.0
4  2023-10-29 00:04:00          1      -65.0

In [23]:
link_rawdata_melted['rsl_value'].isna().sum()

4034354

In [25]:
link_rawdata_melted[~link_rawdata_melted['rsl_value'].isna()].shape

(32452469, 3)

In [26]:
link_rawdata_melted = link_rawdata_melted[~link_rawdata_melted['rsl_value'].isna()]

In [27]:
link_rawdata_melted.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32452469 entries, 0 to 36486822
Data columns (total 3 columns):
 #   Column      Dtype
---  ------      -----
 0   Datetime    object
 1   sublink_id  object
 2   rsl_value   float64
dtypes: float64(1), object(2)
memory usage: 990.4+ MB

In [5]:
pd.options.mode.copy_on_write = True

In [30]:
link_rawdata_melted['sublink_id'] = pd.to_numeric(link_rawdata_melted['sublink_id'])

In [32]:
link_rawdata_melted.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32452469 entries, 0 to 36486822
Data columns (total 3 columns):
 #   Column      Dtype
---  ------      -----
 0   Datetime    object
 1   sublink_id  int64
 2   rsl_value   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 990.4+ MB

## Merge link metadeta with rawdata

In [33]:
# Merge the dataframes
merged_link_df = pd.merge(link_rawdata_melted, link_metadata_df, on='sublink_id', how='left')

In [34]:
merged_link_df.shape

(32452469, 11)

In [35]:
merged_link_df.to_csv(open_mesh_path+"wireless_data_merged.csv", index=False)

## 2. Load merged wireless data

In [4]:
merged_link_df = pd.read_csv(open_mesh_path+"wireless_data_merged.csv")

In [6]:
merged_link_df.shape

(32452469, 11)

In [7]:
merged_link_df.head()

,Datetime,sublink_id,rsl_value,frequency,length,site_0_lat,site_0_lon,site_1_lat,site_1_lon,rsl,polarization
0,2023-10-29 00:00:00,1,-65.0,62640,623.0,40.729552,-73.945949,40.73391,-73.950594,-60.0,Vertical
1,2023-10-29 00:01:00,1,-65.0,62640,623.0,40.729552,-73.945949,40.73391,-73.950594,-60.0,Vertical
2,2023-10-29 00:02:00,1,-65.0,62640,623.0,40.729552,-73.945949,40.73391,-73.950594,-60.0,Vertical
3,2023-10-29 00:03:00,1,-65.0,62640,623.0,40.729552,-73.945949,40.73391,-73.950594,-60.0,Vertical
4,2023-10-29 00:04:00,1,-65.0,62640,623.0,40.729552,-73.945949,40.73391,-73.950594,-60.0,Vertical

In [8]:
merged_link_df.drop(columns=['polarization'], inplace=True)

In [9]:
merged_link_df.shape

(32452469, 10)

## find nearest coordinate code

In [9]:
LATITUDE   LONGITUDE 
40.778980  -73.969250
40.701214  -74.009028

SyntaxError: invalid syntax (238511568.py, line 1)

In [10]:
import math

def find_nearest_coordinate(reference_point):
    """
    Finds the nearest coordinate in a set to a given reference point.

    Args:
        reference_point (tuple): A tuple (x, y) representing the reference point.
        coordinate_set (list): A list of tuples, where each tuple (x, y) 
                               represents a coordinate in the set.

    Returns:
        tuple: The nearest coordinate from the coordinate_set to the reference_point.
               Returns None if the coordinate_set is empty.
    """
    coordinate_set = [[40.778980, -73.969250],[40.701214, -74.009028]]
    nearest_coord = None
    min_distance = float('inf')  # Initialize with a very large number

    for coord in coordinate_set:
        # Calculate Euclidean distance
        distance = math.sqrt((reference_point[0] - coord[0])**2 + (reference_point[1] - coord[1])**2)

        if distance < min_distance:
            min_distance = distance
            nearest_coord = coord
    return nearest_coord

### Using sample df for lat-lon processing

In [11]:
sample_df = merged_link_df.head(10000)

In [12]:
sample_df.shape

(10000, 10)

In [13]:
sample_df.columns

Index(['Datetime', 'sublink_id', 'rsl_value', 'frequency', 'length',
       'site_0_lat', 'site_0_lon', 'site_1_lat', 'site_1_lon', 'rsl'],
      dtype='object')

In [14]:
sample_df[['site_0_lat', 'site_0_lon']].value_counts()

site_0_lat  site_0_lon
40.729552   -73.945949    10000
dtype: int64

In [15]:
find_nearest_coordinate([40.729552, -73.945949])

[40.77898, -73.96925]

In [16]:
#sample_df[['site_0_nearest_lat', 'site_0_nearest_lon']] = sample_df[['site_0_lat', 'site_0_lon']].apply(find_nearest_coordinate, result_type='expand')
sample_df[['site_0_lat', 'site_0_lon']].apply(find_nearest_coordinate, result_type='expand')

   site_0_lat  site_0_lon
0    40.77898   40.701214
1   -73.96925  -74.009028

In [17]:
sample_df.apply(lambda row: find_nearest_coordinate([row['site_1_lat'], row['site_1_lon']]), axis=1, result_type='expand').value_counts()

0         1
40.77898  -73.96925    10000
dtype: int64

In [28]:
merged_link_df.head(100000).apply(lambda row: find_nearest_coordinate([row['site_0_lat'], row['site_0_lon']]), axis=1, result_type='expand')

              0         1
0      40.77898 -73.96925
1      40.77898 -73.96925
2      40.77898 -73.96925
3      40.77898 -73.96925
4      40.77898 -73.96925
...         ...       ...
99995  40.77898 -73.96925
99996  40.77898 -73.96925
99997  40.77898 -73.96925
99998  40.77898 -73.96925
99999  40.77898 -73.96925

[100000 rows x 2 columns]

In [11]:
merged_link_df[['nr_site_0_lat', 'nr_site_0_lon']] = merged_link_df.apply(lambda row: find_nearest_coordinate([row['site_0_lat'], row['site_0_lon']]), axis=1, result_type='expand')

In [12]:
merged_link_df.shape

(32452469, 12)

In [13]:
merged_link_df['rsl_value'].isna().sum()

0

In [14]:
merged_link_df.to_csv(open_mesh_path+"wireless_data_merged_nearest_coord.csv", index=False)

In [15]:
merged_link_df.drop(columns=['site_0_lat', 'site_0_lon', 'site_1_lat', 'site_1_lon'], inplace=True)

In [16]:
merged_link_df.shape

(32452469, 8)

In [17]:
merged_link_df.to_csv(open_mesh_path+"wireless_data_merged_nearest_coord_1.csv", index=False)

## Checkpoint 2: Wireless data with rsl_value, frequency, sublink_id, lat, lon, datetime

In [37]:
merged_link_df = pd.read_csv(open_mesh_path+"wireless_data_merged_nearest_coord_1.csv")

In [18]:
merged_link_df.columns

Index(['Datetime', 'sublink_id', 'rsl_value', 'frequency', 'length', 'rsl',
       'nr_site_0_lat', 'nr_site_0_lon'],
      dtype='object')

In [19]:
merged_link_df[['nr_site_0_lat', 'nr_site_0_lon']].value_counts()

nr_site_0_lat  nr_site_0_lon
40.701214      -74.009028       25561103
40.778980      -73.969250        6891366
dtype: int64

In [20]:
merged_link_df.head()

,Datetime,sublink_id,rsl_value,frequency,length,rsl,nr_site_0_lat,nr_site_0_lon
0,2023-10-29 00:00:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
1,2023-10-29 00:01:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
2,2023-10-29 00:02:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
3,2023-10-29 00:03:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
4,2023-10-29 00:04:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925

In [21]:
merged_link_df.shape

(32452469, 8)

In [38]:
merged_link_df[['site_1_lat', 'site_1_lon']].value_counts()

site_1_lat  site_1_lon
40.724676   -73.980730    1515496
40.693888   -73.906380    1374870
40.725616   -73.947094     688894
40.725903   -73.983635     685085
40.672546   -73.964447     684165
                           ...
40.693819   -73.906361     278022
40.656600   -73.999300     261328
40.675430   -73.980580     221973
40.725684   -73.954130     204904
40.689586   -73.951203     178499
Length: 78, dtype: int64

In [57]:
find_nearest_coordinate([40.729552, -73.945949])

[40.77898, -73.96925]