In [182]:
import pandas as pd

In [1]:
import pandas as pd
import glob
import os

In [184]:
# Define the path to your directory containing Excel files
# You can use a wildcard '*' to match all Excel files (.xlsx or .xls): 
#72622*.csv
excel_files_path = "c:/Users/ukhan/Downloads/2024/*.csv"

In [122]:
# Get a list of all Excel file paths in the specified directory
# glob.glob() returns a list of file paths matching the pattern
excel_files = glob.glob(excel_files_path)

In [116]:
excel_files

['c:/Users/ukhan/Downloads/2024\\72605014745.csv',
 'c:/Users/ukhan/Downloads/2024\\72605504743.csv',
 'c:/Users/ukhan/Downloads/2024\\72605654791.csv',
 'c:/Users/ukhan/Downloads/2024\\72606014764.csv',
 'c:/Users/ukhan/Downloads/2024\\72606464709.csv',
 'c:/Users/ukhan/Downloads/2024\\72607014606.csv',
 'c:/Users/ukhan/Downloads/2024\\72607314615.csv',
 'c:/Users/ukhan/Downloads/2024\\72607714616.csv',
 'c:/Users/ukhan/Downloads/2024\\72607994601.csv',
 'c:/Users/ukhan/Downloads/2024\\72608304836.csv',
 'c:/Users/ukhan/Downloads/2024\\72611454771.csv',
 'c:/Users/ukhan/Downloads/2024\\72611554740.csv',
 'c:/Users/ukhan/Downloads/2024\\72611694765.csv',
 'c:/Users/ukhan/Downloads/2024\\72613014755.csv',
 'c:/Users/ukhan/Downloads/2024\\72614054742.csv',
 'c:/Users/ukhan/Downloads/2024\\72614594705.csv',
 'c:/Users/ukhan/Downloads/2024\\72615554736.csv',
 'c:/Users/ukhan/Downloads/2024\\72616094700.csv',
 'c:/Users/ukhan/Downloads/2024\\72616354770.csv',
 'c:/Users/ukhan/Downloads/2024\\72616454728.csv',
 'c:/Users/ukhan/Downloads/2024\\72616594721.csv',
 'c:/Users/ukhan/Downloads/2024\\72616654781.csv',
 'c:/Users/ukhan/Downloads/2024\\72617014742.csv',
 'c:/Users/ukhan/Downloads/2024\\72618354772.csv',
 'c:/Users/ukhan/Downloads/2024\\72618494709.csv',
 'c:/Users/ukhan/Downloads/2024\\72618514605.csv',
 'c:/Users/ukhan/Downloads/2024\\72619094626.csv',
 'c:/Users/ukhan/Downloads/2024\\72619614610.csv',
 'c:/Users/ukhan/Downloads/2024\\72622394725.csv',
 'c:/Users/ukhan/Downloads/2024\\72622564776.csv',
 'c:/Users/ukhan/Downloads/2024\\72622794790.csv',
 'c:/Users/ukhan/Downloads/2024\\72622894740.csv',
 'c:/Users/ukhan/Downloads/2024\\72628494836.csv',
 'c:/Users/ukhan/Downloads/2024\\72635094860.csv',
 'c:/Users/ukhan/Downloads/2024\\72635594871.csv',
 'c:/Users/ukhan/Downloads/2024\\72635794815.csv',
 'c:/Users/ukhan/Downloads/2024\\72635800384.csv',
 'c:/Users/ukhan/Downloads/2024\\72636014840.csv',
 'c:/Users/ukhan/Downloads/2024\\72636404883.csv',
 'c:/Users/ukhan/Downloads/2024\\72637014826.csv',
 'c:/Users/ukhan/Downloads/2024\\72637594817.csv',
 'c:/Users/ukhan/Downloads/2024\\72637914845.csv',
 'c:/Users/ukhan/Downloads/2024\\72638094814.csv',
 'c:/Users/ukhan/Downloads/2024\\72638414817.csv',
 'c:/Users/ukhan/Downloads/2024\\72638594894.csv',
 'c:/Users/ukhan/Downloads/2024\\72638714850.csv',
 'c:/Users/ukhan/Downloads/2024\\72639094849.csv',
 'c:/Users/ukhan/Downloads/2024\\72639100385.csv',
 'c:/Users/ukhan/Downloads/2024\\72639200424.csv',
 'c:/Users/ukhan/Downloads/2024\\72639404874.csv',
 'c:/Users/ukhan/Downloads/2024\\72639514808.csv',
 'c:/Users/ukhan/Downloads/2024\\72639600422.csv',
 'c:/Users/ukhan/Downloads/2024\\72640014839.csv',
 'c:/Users/ukhan/Downloads/2024\\72640404865.csv',
 'c:/Users/ukhan/Downloads/2024\\72640594869.csv',
 'c:/Users/ukhan/Downloads/2024\\72640904897.csv',
 'c:/Users/ukhan/Downloads/2024\\72641014837.csv',
 'c:/Users/ukhan/Downloads/2024\\72641304875.csv',
 'c:/Users/ukhan/Downloads/2024\\72641404873.csv',
 'c:/Users/ukhan/Downloads/2024\\72641594854.csv',
 'c:/Users/ukhan/Downloads/2024\\72641614921.csv',
 'c:/Users/ukhan/Downloads/2024\\72641754911.csv',
 'c:/Users/ukhan/Downloads/2024\\72641854912.csv',
 'c:/Users/ukhan/Downloads/2024\\72641994929.csv',
 'c:/Users/ukhan/Downloads/2024\\72642494818.csv',
 'c:/Users/ukhan/Downloads/2024\\72642504841.csv',
 'c:/Users/ukhan/Downloads/2024\\72642604895.csv',
 'c:/Users/ukhan/Downloads/2024\\72642754908.csv',
 'c:/Users/ukhan/Downloads/2024\\72643014920.csv',
 'c:/Users/ukhan/Downloads/2024\\72643514991.csv',
 'c:/Users/ukhan/Downloads/2024\\72643694930.csv',
 'c:/Users/ukhan/Downloads/2024\\72643794940.csv',
 'c:/Users/ukhan/Downloads/2024\\72643894994.csv',
 'c:/Users/ukhan/Downloads/2024\\72644014925.csv',
 'c:/Users/ukhan/Downloads/2024\\72644404963.csv',
 'c:/Users/ukhan/Downloads/2024\\72644904891.csv',
 'c:/Users/ukhan/Downloads/2024\\72645014898.csv',
 'c:/Users/ukhan/Downloads/2024\\72645204826.csv',
 'c:/Users/ukhan/Downloads/2024\\72645594897.csv',
 'c:/Users/ukhan/Downloads/2024\\72645694855.csv',
 'c:/Users/ukhan/Downloads/2024\\72645704825.csv',
 'c:/Users/ukhan/Downloads/2024\\72645804824.csv',
 'c:/Users/ukhan/Downloads/2024\\72646314897.csv',
 'c:/Users/ukhan/Downloads/2024\\72646454834.csv',
 'c:/Users/ukhan/Downloads/2024\\72646594890.csv',
 'c:/Users/ukhan/Downloads/2024\\72646654917.csv',
 'c:/Users/ukhan/Downloads/2024\\72646754909.csv',
 'c:/Users/ukhan/Downloads/2024\\72646854913.csv',
 'c:/Users/ukhan/Downloads/2024\\72648094853.csv',
 'c:/Users/ukhan/Downloads/2024\\72648794896.csv',
 'c:/Users/ukhan/Downloads/2024\\72649804925.csv',
 'c:/Users/ukhan/Downloads/2024\\72649994971.csv',
 'c:/Users/ukhan/Downloads/2024\\72650014972.csv',
 'c:/Users/ukhan/Downloads/2024\\72650254832.csv',
 'c:/Users/ukhan/Downloads/2024\\72650354833.csv',
 'c:/Users/ukhan/Downloads/2024\\72650454838.csv',
 'c:/Users/ukhan/Downloads/2024\\72650504845.csv',
 'c:/Users/ukhan/Downloads/2024\\72650604840.csv',
 'c:/Users/ukhan/Downloads/2024\\72650754907.csv',
 'c:/Users/ukhan/Downloads/2024\\72650894973.csv',
 'c:/Users/ukhan/Downloads/2024\\72650904898.csv',
 'c:/Users/ukhan/Downloads/2024\\72651014944.csv',
 'c:/Users/ukhan/Downloads/2024\\72651494032.csv',
 'c:/Users/ukhan/Downloads/2024\\72651594902.csv',
 'c:/Users/ukhan/Downloads/2024\\72651624024.csv',
 'c:/Users/ukhan/Downloads/2024\\72651794039.csv',
 'c:/Users/ukhan/Downloads/2024\\72651894990.csv',
 'c:/Users/ukhan/Downloads/2024\\72651994993.csv',
 'c:/Users/ukhan/Downloads/2024\\72652594911.csv',
 'c:/Users/ukhan/Downloads/2024\\72653094943.csv',
 'c:/Users/ukhan/Downloads/2024\\72653994056.csv',
 'c:/Users/ukhan/Downloads/2024\\72654014936.csv',
 'c:/Users/ukhan/Downloads/2024\\72654404958.csv',
 'c:/Users/ukhan/Downloads/2024\\72654594950.csv',
 'c:/Users/ukhan/Downloads/2024\\72654614946.csv',
 'c:/Users/ukhan/Downloads/2024\\72654704931.csv',
 'c:/Users/ukhan/Downloads/2024\\72654804971.csv',
 'c:/Users/ukhan/Downloads/2024\\72654954905.csv',
 'c:/Users/ukhan/Downloads/2024\\72655014926.csv',
 'c:/Users/ukhan/Downloads/2024\\72655304951.csv',
 'c:/Users/ukhan/Downloads/2024\\72655454906.csv',
 'c:/Users/ukhan/Downloads/2024\\72655594938.csv',
 'c:/Users/ukhan/Downloads/2024\\72655614992.csv',
 'c:/Users/ukhan/Downloads/2024\\72655714910.csv',
 'c:/Users/ukhan/Downloads/2024\\72655804914.csv',
 'c:/Users/ukhan/Downloads/2024\\72655994976.csv',
 'c:/Users/ukhan/Downloads/2024\\72656024025.csv',
 'c:/Users/ukhan/Downloads/2024\\72656194997.csv',
 'c:/Users/ukhan/Downloads/2024\\72656204943.csv',
 'c:/Users/ukhan/Downloads/2024\\72656394969.csv',
 'c:/Users/ukhan/Downloads/2024\\72656404967.csv',
 'c:/Users/ukhan/Downloads/2024\\72656504948.csv',
 'c:/Users/ukhan/Downloads/2024\\72656704980.csv',
 'c:/Users/ukhan/Downloads/2024\\72656804961.csv',
 'c:/Users/ukhan/Downloads/2024\\72656904933.csv',
 'c:/Users/ukhan/Downloads/2024\\72657294966.csv',
 'c:/Users/ukhan/Downloads/2024\\72657494985.csv',
 'c:/Users/ukhan/Downloads/2024\\72657594960.csv',
 'c:/Users/ukhan/Downloads/2024\\72657794974.csv',
 'c:/Users/ukhan/Downloads/2024\\72657804944.csv',
 'c:/Users/ukhan/Downloads/2024\\72657994963.csv',
 'c:/Users/ukhan/Downloads/2024\\72658014922.csv',
 'c:/Users/ukhan/Downloads/2024\\72658304941.csv',
 'c:/Users/ukhan/Downloads/2024\\72658414927.csv',
 'c:/Users/ukhan/Downloads/2024\\72658514954.csv',
 'c:/Users/ukhan/Downloads/2024\\72658694948.csv',
 'c:/Users/ukhan/Downloads/2024\\72658794927.csv',
 'c:/Users/ukhan/Downloads/2024\\72658804956.csv',
 'c:/Users/ukhan/Downloads/2024\\72658994968.csv',
 'c:/Users/ukhan/Downloads/2024\\72659014929.csv',
 'c:/Users/ukhan/Downloads/2024\\72659304946.csv',
 'c:/Users/ukhan/Downloads/2024\\72659604978.csv',
 'c:/Users/ukhan/Downloads/2024\\72660304974.csv',
 'c:/Users/ukhan/Downloads/2024\\72660500386.csv',
 'c:/Users/ukhan/Downloads/2024\\72662024090.csv',
 'c:/Users/ukhan/Downloads/2024\\72662524006.csv',
 'c:/Users/ukhan/Downloads/2024\\72662604864.csv',
 'c:/Users/ukhan/Downloads/2024\\72662794037.csv',
 'c:/Users/ukhan/Downloads/2024\\72665094023.csv',
 'c:/Users/ukhan/Downloads/2024\\72665494054.csv',
 'c:/Users/ukhan/Downloads/2024\\72666024029.csv',
 'c:/Users/ukhan/Downloads/2024\\72666494173.csv',
 'c:/Users/ukhan/Downloads/2024\\72666524062.csv',
 'c:/Users/ukhan/Downloads/2024\\72666724048.csv',
 'c:/Users/ukhan/Downloads/2024\\72667624087.csv',
 'c:/Users/ukhan/Downloads/2024\\72667904969.csv',
 'c:/Users/ukhan/Downloads/2024\\72668254914.csv',
 'c:/Users/ukhan/Downloads/2024\\72668594052.csv',
 'c:/Users/ukhan/Downloads/2024\\72669024057.csv',
 'c:/Users/ukhan/Downloads/2024\\72670024045.csv',
 'c:/Users/ukhan/Downloads/2024\\72671024164.csv',
 'c:/Users/ukhan/Downloads/2024\\72672024061.csv',
 'c:/Users/ukhan/Downloads/2024\\72676494163.csv',
 'c:/Users/ukhan/Downloads/2024\\72677024033.csv',
 'c:/Users/ukhan/Downloads/2024\\72677624036.csv',
 'c:/Users/ukhan/Downloads/2024\\72677794055.csv',
 'c:/Users/ukhan/Downloads/2024\\72679724132.csv',
 'c:/Users/ukhan/Downloads/2024\\72679824150.csv',
 'c:/Users/ukhan/Downloads/2024\\72681024131.csv',
 'c:/Users/ukhan/Downloads/2024\\72681394195.csv',
 'c:/Users/ukhan/Downloads/2024\\72681524106.csv',
 'c:/Users/ukhan/Downloads/2024\\72681604110.csv',
 'c:/Users/ukhan/Downloads/2024\\72681724154.csv',
 'c:/Users/ukhan/Downloads/2024\\72681894194.csv',
 'c:/Users/ukhan/Downloads/2024\\72682404112.csv',
 'c:/Users/ukhan/Downloads/2024\\72683094185.csv',
 'c:/Users/ukhan/Downloads/2024\\72683604201.csv',
 'c:/Users/ukhan/Downloads/2024\\72683724162.csv',
 'c:/Users/ukhan/Downloads/2024\\72686524196.csv',
 'c:/Users/ukhan/Downloads/2024\\72687300452.csv',
 'c:/Users/ukhan/Downloads/2024\\72687594107.csv',
 'c:/Users/ukhan/Downloads/2024\\72687600387.csv',
 'c:/Users/ukhan/Downloads/2024\\72688024155.csv',
 'c:/Users/ukhan/Downloads/2024\\72688194273.csv',
 'c:/Users/ukhan/Downloads/2024\\72688304113.csv',
 'c:/Users/ukhan/Downloads/2024\\72688424148.csv',
 'c:/Users/ukhan/Downloads/2024\\72688524152.csv',
 'c:/Users/ukhan/Downloads/2024\\72688624130.csv',
 'c:/Users/ukhan/Downloads/2024\\72688799999.csv',
 'c:/Users/ukhan/Downloads/2024\\72690424231.csv',
 'c:/Users/ukhan/Downloads/2024\\72691724284.csv',
 'c:/Users/ukhan/Downloads/2024\\72692024230.csv',
 'c:/Users/ukhan/Downloads/2024\\72693024221.csv',
 'c:/Users/ukhan/Downloads/2024\\72694024232.csv',
 'c:/Users/ukhan/Downloads/2024\\72694524202.csv',
 'c:/Users/ukhan/Downloads/2024\\72695024285.csv',
 'c:/Users/ukhan/Downloads/2024\\72695994281.csv',
 'c:/Users/ukhan/Downloads/2024\\72698024229.csv',
 'c:/Users/ukhan/Downloads/2024\\72698524242.csv',
 'c:/Users/ukhan/Downloads/2024\\72698694261.csv',
 'c:/Users/ukhan/Downloads/2024\\72698824219.csv']

In [66]:
df = pd.read_csv('c:/Users/ukhan/Downloads/2024/72622394725.csv')

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\3037080109.py:1: DtypeWarning: Columns (2,34,35,41,42,49,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('c:/Users/ukhan/Downloads/2024/72622394725.csv')

In [67]:
df.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL', 'WND', 'CIG',
       'VIS', 'TMP', 'DEW', 'SLP', 'AA1', 'AA2', 'AA3', 'AB1', 'AD1', 'AE1',
       'AH1', 'AH2', 'AH3', 'AH4', 'AH5', 'AH6', 'AI1', 'AI2', 'AI3', 'AI4',
       'AI5', 'AI6', 'AL1', 'AN1', 'AT1', 'AT2', 'AT3', 'AT4', 'AT5', 'AT6',
       'AT7', 'AU1', 'AU2', 'AU3', 'AW1', 'AW2', 'AW3', 'AW4', 'AX1', 'AX2',
       'AX3', 'GA1', 'GA2', 'GA3', 'GD1', 'GD2', 'GD3', 'GE1', 'GF1', 'KA1',
       'KA2', 'KB1', 'KB2', 'KB3', 'KC1', 'KC2', 'KD1', 'KD2', 'KE1', 'KG1',
       'KG2', 'MA1', 'MD1', 'MF1', 'MG1', 'MH1', 'MK1', 'MV1', 'MW1', 'OC1',
       'OD1', 'OE1', 'OE2', 'OE3', 'RH1', 'RH2', 'RH3', 'WA1', 'REM', 'EQD'],
      dtype='object')

In [68]:
df['LATITUDE'].value_counts()

44.93341    13278
Name: LATITUDE, dtype: int64

In [54]:
search_string_re = r"ny|new york|NY"

In [ ]:
df['NAME'].str.contains("NO", case=False, na=False) 
.str.contains('an', regex=True, case=False)

In [55]:
df[df['NAME'].str.contains(search_string_re, regex=True, na=False)].head()

Empty DataFrame
Columns: [STATION, DATE, SOURCE, LATITUDE, LONGITUDE, ELEVATION, NAME, REPORT_TYPE, CALL_SIGN, QUALITY_CONTROL, WND, CIG, VIS, TMP, DEW, SLP, AA1, AA2, AA3, AJ1, AY1, AY2, GA1, GA2, GA3, GE1, GF1, IA1, KA1, KA2, MA1, MD1, MW1, OC1, OD1, SA1, UA1, REM, EQD]
Index: []

[0 rows x 39 columns]

In [70]:
df[['LATITUDE','LONGITUDE']].value_counts()

LATITUDE  LONGITUDE
44.93341  -74.84836    13278
dtype: int64

In [72]:
df.shape

(13278, 92)

In [75]:
df[(df['LATITUDE']>44) & (df['LONGITUDE']<-74)].shape

(13278, 92)

In [ ]:
((link_metadata_df['site_0_lat']>40.5) & (link_metadata_df['site_0_lat']<40.9)).sum()
((link_metadata_df['site_0_lon']<-73.9) & (link_metadata_df['site_0_lon']>-74.1)).sum()

In [103]:
lat = [44.5, 45]
lon = [-75.1, -73.9]

In [104]:
df[df['LATITUDE'].between(lat[0], lat[1], inclusive='both')].shape

(13278, 92)

In [105]:
df[df['LONGITUDE'].between(lon[0], lon[1], inclusive='both')].shape

(13278, 92)

In [106]:
df[(df['LATITUDE'].between(lat[0], lat[1], inclusive='both') & df['LONGITUDE'].between(lon[0], lon[1], inclusive='both'))].shape

(13278, 92)

In [108]:
df.shape[0]>0

True

In [124]:
#lat = [40.6, 40.8]
#lon = [-74.01, -73.92]
#720*.csv
lat = [39, 42]
lon = [-76, -72]

In [125]:
# Create an empty list to store the individual DataFrames
all_dfs = []

# Loop through each Excel file found
for file_path in excel_files:
    try:
        # Read the Excel file into a Pandas DataFrame
        df = pd.read_csv(file_path)
        
        df = df[(df['LATITUDE'].between(lat[0], lat[1], inclusive='both') & df['LONGITUDE'].between(lon[0], lon[1], inclusive='both'))]
        if df.shape[0]>0:
            # Optional: Add a column to identify the source file
            df['source_file'] = os.path.basename(file_path)
            # Append the DataFrame to the list
            all_dfs.append(df)
            print("lat_lon found in file:"+file_path)
        
    except Exception as e:
        print(f"Error reading {file_path}: {e}")

# Concatenate all individual DataFrames into a single DataFrame
if all_dfs:
    combined_df = pd.concat(all_dfs, ignore_index=True)
    print("Combined DataFrame created successfully.")
    print(combined_df.head()) # Display the first few rows of the combined DataFrame
else:
    print("No Excel files found or no DataFrames were successfully read.")

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,21,26,29,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,25,26,28,30,32,33,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,25,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,20,27,28,30,33,35,36,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,19,20,21,27,28,30,32,34,35,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,25,26,28,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,24,25,27,30,31,33,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,24,25,27,30,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25,26,28,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26,27,29,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,26,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25,26,28,31,32,33,35,36,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,22,25,26,28,30,31,32,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,24,25,27,29,30,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25,26,28,31,32,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25,26,28,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (33,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,25,26,28,31,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,25,26,28,30,32,33,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25,26,28,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25,26,28,31,32,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25,26,28,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,32,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24,26,30,31,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,20,21,28,29,31,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,26,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,26,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,26,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,24,27,28,30,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,19,24,27,28,30,32,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,23,26,27,29,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,26,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,19,24,27,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,21,22,23,30,31,33,35,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,19,24,27,28,30,32,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,18,19,24,27,28,30,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,19,22,23,24,25,26,34,35,36,38,41,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,24,27,28,30,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26,35,36,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,24,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,25,28,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26,27,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26,35,36,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,21,22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,21,22,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,21,22,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,19,27,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,21,22,28,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,25,28,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,22,25,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72030464752.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24,25,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,26,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,26,27,29,30,37,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72032464753.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,24,27,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,19,20,21,22,23,24,26,27,28,35,39,40,41,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (33,39,40,43,44,47,74,76,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,25,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,24,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,23,29,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,17,18,19,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72040700462.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72040800136.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,17,18,23,24,25,29,30,34,37,38,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,24,40,41,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,22,24,27,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,23,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,16,17,18,19,20,21,22,23,24,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,26,30,34,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,19,20,21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,27,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,29,39,40,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,21,22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25,29,39,40,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,25,28,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,20,21,23,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72054500169.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72055399999.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,24,26,27,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,30,50,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,25,28,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72058100178.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,24,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,20,25,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,24,25,30,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,23,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,20,22,23,33,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,19,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45,50,51,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,25,26,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,24,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,24,26,28,29,30,33,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,23,25,26,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24,26,29,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,24,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,19,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,21,23,24,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,21,22,23,25,26,28,29,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,30,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,25,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,20,21,26,27,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,51,52,56,83,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,40,43,46,47) have mixed types. Specify dtype option on import or set low_memory=False.

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72209864761.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (45,50,54,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,22,23,24,25,26,27,28,29,30,31,32,33,36,53,58,72,73,85,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,45,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,53,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,25,28,31,32,33,34,35,36,37,38,47,48,50,51,55,56,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,24,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,25,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,20,21,22,35,44,45,46,47,48,49,50,51,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,44,49,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,20,26,32,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,50,51,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,23,24,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,25,27,28,29,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,26,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,22,23,24,25,26,27,34,35,36,51,82) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (48,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,24,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,51,52,56,60,85,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,45,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,26,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (35,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,45,50,53,54,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,38,41,44,45,47,48,60,61,62,63,64,65,66,67,68,69,73,74,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (33,38,40,41,42,45,46,47,49,50,71,77,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,44,45,56,63,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,18,26,27,30,31,34,49,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (45,50,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,27,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,26,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24,26,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,20,21,22,23,24,25,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,38,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72224754785.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,25,28,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,50,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,40,41,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,23,24,25,26,27,31,32,35,36,49,50,51,52,53,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (40,43,44,68) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,54,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,40,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,40,44,49,53,57,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,45,50,54,93) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,40,44,49,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,24,25,26,27,28,29,30,31,32,33,34,35,56,68,69,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,18,22,23,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,29,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,54,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (33,38,42,47,50,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,62,87,88,97) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,20,21,27,33,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,43,44,45,47,48,49,50,51,52,53,54,56,57,59,60,65,66,67,68,69,70,71,72,73,74,75,76,79,80,81,82,83,84,85,86,87,88,89,90,91,92) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,45,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,45,50,51,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,40,50,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,52,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,47,52,56,60,88,97) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,45,50,85,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,52,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,52,83,92) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,45,50,54,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,35,36,37,42,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,39,43,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,44,45,64,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,48,79,80,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,44,49,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,38,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,81,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,47,52,56,61,88,91,100) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,41,45,57,58,59,60,61,62,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (71,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,47,78,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,52,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45,50,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,44,54,55,86,88,97) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,38,48,49,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,8,18,21,22,23,24,25,26,27,28,31,32,33,34,35,36,39,40,53,54,57,59,60,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,27,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,29,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,47,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,51,52,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,40,41,51,52,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,45,50,54,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,54,55,93) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,42,46,51,52,56,96) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,51,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,25,29,34,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,34,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (35,37,43,47,52,53,57,80,81,84,88,95,96,97,98) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,20,21,31,45,46) have mixed types. Specify dtype option on import or set low_memory=False.

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72407093730.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72407493780.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,44,47,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72407513735.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72407754779.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,47,52,55,60,85,96) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72408013739.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72408454760.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,38,41,44,45,48,72,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72408594732.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72408813707.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72409014780.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,38,41,45,48,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,41,45,48,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72409454743.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,42,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72409514792.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72409614706.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72409754738.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,42,43,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,25,31,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24,26,29,41,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,47,52,83,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,43,44,47,50,51,52,53,54,55,66,67,68,69,70,71,72,73,74,75,78,80,81,82,89,90,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,40,44,49,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,49,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72418013781.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,54,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,47,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,24,28,33,48,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,38,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,82,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,38,39,44,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,42,46,47,48,51,80,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,49,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (47,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,25,27,28,29,43,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,42,46,50,76,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (47,52,60,88,97) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (42,46,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,42,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,45,50,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,54,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,47,60,61,62,63,64,65,66,67,71,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,22,23,24,25,27,28,29,30,34,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,44,55,86,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,42,53,61,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,45,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,54,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (47,52,56,85,96) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,25,28,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,42,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,18,36,42,43,44,47,48,52,53,57,89,98) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,20,21,26,27,37,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,42,43,44,48,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,40,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,42,46,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,47,54,55,86,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,42,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,42,49,53,81,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,44,58,92) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,37,38,39,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,43,48,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (51,55,60,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,40,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,40,41,45,50,54,82,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,35,37,51,52,55,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,40,50,71,72,75,86,87,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,46,49,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,43,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,40,44,49,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (44,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40,43,44,48,49,52,53,72,73,76,87,88,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,42,47,50,69,70,73,84,85,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,48,67,68,71,82,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (48,53,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (44,48,53,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,40,43,44,48,49,52,77,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,42,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (42,46,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (40,41,50,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,42,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,18,38,41,44,45,47,54,55,71,74,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,42,46,67,68,71,82,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72501504789.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72501654790.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (45,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,53,58,83,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72502014734.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,40,41,44,45,48,49,50,53,78,80,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72502594741.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72502754788.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72502964707.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72503014732.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,44,45,48,49,53,54,58,87,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,45,48,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72503614757.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72503794745.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72503814714.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,42,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,46,49,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72504094702.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72504514758.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,48,49,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,44,48,53,56,57,86,98) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72504614707.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72505004781.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72505394728.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,42,46,49,74,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,48,75,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,40,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,44,52,60,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,42,46,49,50,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (46,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72508014740.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72508454767.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45,48,72,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (46,49,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72508654734.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72508714752.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40,43,47,50,74,76,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,42,43,47,52,84,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,40,43,46,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,43,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,42,45,49,52,53,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72510314712.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,40,43,46,47,50,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,42,45,46,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72510954782.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72511354786.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (40,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (40,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,43,54,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,44,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72513014777.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\72514554746.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,43,44,45,48,52,54,55,66,67,68,69,70,71,72,73,74,75,78,80,81,82,89,90,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (42,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,44,54,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45,69) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72517014737.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (45,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,42,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,44,55,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,27,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,37,60,85,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,42,46,49,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (85,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,42,47,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,47,52,55,56,57,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (47,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,24,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,45,56,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,44,45,46,87,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,57,62,89,92) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,50,51,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,44,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,46,51,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (44,45,49,54,57,58,86,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,35,42,46,51,82) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,48,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,40,57,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,23,24,25,26,29,32,33,34,35,36,45,46,47,49,50,53,54,56,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,55,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,46,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (55,63) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,25,27,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,46,49,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,46,49,68) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,23,24,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,28,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,24,26,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,44,48,53,60,87,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,44,48,53,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\72543454789.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,47,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,44,48,53,56,57,92) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,42,46,51,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (45,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,41,42,43,47,52,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,42,46,51,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,22,23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,30,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,23,24,25,26,27,28,29,30,31,32,33,36,43,44,47,48,52,53,74,75,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,41,42,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,44,48,56,61,88,90,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,47,52,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,29,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,40,43,44,46,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,44,45,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,40,43,47,50,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,42,43,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,42,47,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,40,41,44,47,48,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,44,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,42,45,46,49,50,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,44,45,49,54,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,24,25,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,29,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,42,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,40,43,46,47,50,51,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,22,23,24,25,26,27,28,29,30,31,32,33,36,54,55,71,72,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (42,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,44,48,52,53,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,43,44,45,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,42,43,44,45,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,46,50,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,42,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,41,45,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,20,28,34,45,46,47,48,49,50,51,52,55,57,65,66,67) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,44,45,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,40,43,46,47,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40,43,47,50,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (35,37,44,47,51,54,73,74,77,88,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,42,45,46,49,68,69,72,76,83,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,49,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,42,43,44,45,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (40,43,47,48,52,60) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,42,46,48,49,68,69,72,76,83,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (35,37,46,50,53,72,73,76,87,88,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,42,45,49,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,25,28,29,32,33,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,68) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (43,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,42,43,46,49,50,51,78,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40,41,44,47,48,50,51,52,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,41,42,45,48,76,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,39,42,46,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,42,49,52,82,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (42,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,45,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\74000154793.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,37,38,39,40,41,42,43,44,45,46,47,48,49,52,55,60,61,62,63,64,65,66,67,71,72,73,74,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,23,24,25,26,27,30,31,34,35,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,34,35,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,42,46,49,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,23,24,27,28,38,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,19,23,24,25,26,27,30,31,34,35,36,37,51,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,35,37,44,45,56,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,40,41,48,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,42,43,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,24,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40,51,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,43,44,48,53,56,61,86) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\74486094789.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,41,44,45,73) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\74486454787.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\74486514719.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (49,75,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (39,40,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (45,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,44,45,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,43,60,61,62,63,64,65,66,67,71,72,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,39,42,43,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (24,28,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,40,44,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\74596603726.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,35,36,38,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,41,42,46,51,54,75,76,79,90,91,92) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,33,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,45,47,48,49,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (33,42,68) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36,43,46,49,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,26,37,38,40,42,44,45,47,48,50,51,69) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,22,23,24,25,26,27,34,35,36,38,39,41,43,45,46,49,52,70,73) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,17,18,22,23,24,25,26,27,37,38,39,40,41,42,43,44,45,47,48,50,51,53,54,67,68,71,75,76,82,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,19,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,23,25,28,30,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,38,39,70,71,74,85,86,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,47,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,52,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,35,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,45,50,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,43,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,40,43,47,50,55,72,73,76,80,83,89,90,91) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,50,60,71,72,75,79,81,82,88,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (34,35,36,44,49,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (41,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (40,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,23,24,25,26,27,28,29,30,31,32,62,63,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,37,66,67,70,77,83,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,21,22,28,31,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,37,40,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,28,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (19,21,27,30,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,22,23,27,28,32,38,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,22,29,32,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,23,24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,18,19,22,26,32,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,21,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,21,30,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,26,32,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,20,23,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,19,20,21,22,23,28,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,22,35,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,19,20,25,30,34,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,29,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,26,27,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (35,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (28,32,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,19,20,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,26,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (26,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (38,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,21,22,26,29,30,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,23,27,30,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,27,30,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,21,22,23,27,30,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (18,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (37,40,44,47,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (23,26,29,30,45,47,48,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,42,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,41,72,73) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,49,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,68,69) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,41,42,45,48,49,51,64,65,66,67,68,69,70,71,72,73,76,78,79,82,88,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,42,46,49,53,75,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (36,39,42,43,45,64,65,68,73,74,80,81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,18,19,20,21,22,23,24,25,26,27,28,35,36,37,38,43,44,45,46,47,48,49,50,53,54,55,56,57,60,62,63,64,65,66,67,68) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\99475099999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99727099999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99727199999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99728099999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99728499999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99728699999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99728999999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99729099999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99730099999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99737299999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99768799999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99769499999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99769899999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99774399999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99777999999.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\99800299999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99816999999.csv
lat_lon found in file:c:/Users/ukhan/Downloads/2024\99826599999.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,23,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22,24,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20,21,22,24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\99999900379.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,24,26,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\99999903761.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

lat_lon found in file:c:/Users/ukhan/Downloads/2024\99999913724.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (32,33,34,38,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (8,17,18,20,21,50,51,52,53,54,55,56,57,60,61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,25,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,25,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,25,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,43,44,45,46,47,48,49,50) have mixed types. Specify dtype option on import or set low_memory=False.

lat_lon found in file:c:/Users/ukhan/Downloads/2024\99999964756.csv

C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,43,44,45,46,47,48,49,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,44,45,46,47,48,49,50,51,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,48,49,50,51,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (17,18,47,48,49,50,51,52,53,54,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,25,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,22,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,17,18,19,24,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (16,18,19,20,22,24,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,35,38,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,36,40,44,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (2,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (25,26,27,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\ukhan\AppData\Local\Temp\ipykernel_47920\1556742625.py:8: DtypeWarning: Columns (21,22,23,24,27,30,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Combined DataFrame created successfully.
       STATION                 DATE SOURCE  LATITUDE  LONGITUDE  ELEVATION  \
0  72030464752  2024-01-01T00:15:00      4      40.1  -75.26667       92.0
1  72030464752  2024-01-01T00:35:00      4      40.1  -75.26667       92.0
2  72030464752  2024-01-01T00:55:00      4      40.1  -75.26667       92.0
3  72030464752  2024-01-01T01:15:00      4      40.1  -75.26667       92.0
4  72030464752  2024-01-01T01:35:00      4      40.1  -75.26667       92.0

                 NAME REPORT_TYPE CALL_SIGN QUALITY_CONTROL  ...  CU2  CU3  \
0  WINGS FIELD, PA US       FM-15     99999            V020  ...  NaN  NaN
1  WINGS FIELD, PA US       FM-15     99999            V020  ...  NaN  NaN
2  WINGS FIELD, PA US       FM-15     99999            V020  ...  NaN  NaN
3  WINGS FIELD, PA US       FM-15     99999            V020  ...  NaN  NaN
4  WINGS FIELD, PA US       FM-15     99999            V020  ...  NaN  NaN

   CV1  CV2  CV3  CW1  GH1  IB2  KF1  OB1
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[5 rows x 138 columns]

In [126]:
combined_df.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL',
       ...
       'CU2', 'CU3', 'CV1', 'CV2', 'CV3', 'CW1', 'GH1', 'IB2', 'KF1', 'OB1'],
      dtype='object', length=138)

In [127]:
combined_df.shape

(1100065, 138)

In [128]:
combined_df['NAME'].value_counts()

AVONDALE 2 N, PA US                              105486
MILLBROOK 3 W, NY US                             105414
WINGS FIELD, PA US                                26288
CHESTER CO GO CARLSON AIRPORT, PA US              26145
CHESTER AIRPORT, CT US                            26114
                                                  ...
LAKEHURST NAS, NJ US                               5795
SHIP JOHN SHOAL, NJ US                             5468
NEW LONDON LEDGE LEDGE LIGHT WEATHER S, CT US      2646
ATLANTIC CITY MARINA, NJ US                         286
MONTICELLO SULLIVAN, NY US                           36
Name: NAME, Length: 75, dtype: int64

In [129]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100065 entries, 0 to 1100064
Columns: 138 entries, STATION to OB1
dtypes: float64(3), int64(1), object(134)
memory usage: 1.1+ GB

In [2]:
target_path="C:/Users/ukhan/Documents/DataSet/OpenMesh/nceia_noaa/"

In [3]:
#lat = [39, 42]
#lon = [-76, -72]
combined_df.to_csv(target_path+"2024_lat_39__42__lon_-76__-72_1.1M.csv", index=False)

NameError: name 'combined_df' is not defined

In [4]:
#lat = [39, 42]
#lon = [-76, -72]
combined_df = pd.read_csv(target_path+"2024_lat_39__42__lon_-76__-72_1.1M.csv")

C:\Users\ukhan\AppData\Local\Temp\ipykernel_3028\318714253.py:3: DtypeWarning: Columns (2,6,8,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.read_csv(target_path+"2024_lat_39__42__lon_-76__-72_1.1M.csv")

## 2024 data for lat-lon as present under mesh data

In [5]:
lat = [40.6, 40.8]
lon = [-74.01, -73.92]

In [6]:
df=combined_df[(combined_df['LATITUDE'].between(lat[0], lat[1], inclusive='both') & combined_df['LONGITUDE'].between(lon[0], lon[1], inclusive='both'))]

In [7]:
df.shape

(21824, 138)

In [192]:
df.to_csv(target_path+"2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_21K.csv", index=False)

In [8]:
df.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL',
       ...
       'CU2', 'CU3', 'CV1', 'CV2', 'CV3', 'CW1', 'GH1', 'IB2', 'KF1', 'OB1'],
      dtype='object', length=138)

In [9]:
columns_all_na = df.columns[df.isnull().all()].tolist()

In [10]:
len(columns_all_na)

46

In [11]:
df = df.drop(columns=columns_all_na)

In [12]:
df.shape

(21824, 92)

In [13]:
columns_na_gt_10000 = df.columns[df.isna().sum()>10000].to_list()

In [14]:
df = df.drop(columns=columns_na_gt_10000)

In [15]:
df.shape

(21824, 22)

In [16]:
df.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL', 'WND', 'CIG',
       'VIS', 'TMP', 'DEW', 'SLP', 'GD1', 'GE1', 'GF1', 'MA1', 'REM',
       'source_file'],
      dtype='object')

In [198]:
columns_na_gt_100 = df.columns[df.isna().sum()>100].to_list()

In [199]:
df = df.drop(columns=columns_na_gt_100)

In [200]:
df.head()

,STATION,DATE,SOURCE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,CALL_SIGN,QUALITY_CONTROL,WND,CIG,VIS,TMP,DEW,SLP,REM,source_file
115082,72055399999,2024-01-01T00:56:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-15,99999,V020,"260,1,N,0031,1","01524,1,9,N","016093,1,9,9","+0056,1","-0022,1","10164,1",MET088METAR KJRB 010056Z AUTO 26006KT 10SM OVC...,72055399999.csv
115083,72055399999,2024-01-01T01:56:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-15,99999,V020,"260,1,N,0026,1","01524,1,9,N","016093,1,9,9","+0056,1","-0017,1","10164,1",MET088METAR KJRB 010156Z AUTO 26005KT 10SM OVC...,72055399999.csv
115084,72055399999,2024-01-01T02:56:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-15,99999,V020,"250,1,N,0026,1","01463,1,9,N","016093,1,9,9","+0056,1","-0011,1","10164,1",MET100METAR KJRB 010256Z AUTO 25005KT 10SM OVC...,72055399999.csv
115085,72055399999,2024-01-01T03:56:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-15,99999,V020,"260,1,N,0026,1","01463,1,9,N","016093,1,9,9","+0056,1","-0006,1","10165,1",MET098METAR KJRB 010356Z AUTO 26005KT 10SM OVC...,72055399999.csv
115086,72055399999,2024-01-01T04:56:00,4,40.701214,-74.009028,2.13,"PORT AUTH DOWNTN MANHATTAN WALL ST HEL, NY US",FM-15,99999,V020,"250,1,N,0041,1","01402,1,9,N","016093,1,9,9","+0056,1","-0006,1","10167,1",MET095METAR KJRB 010456Z AUTO 25008KT 10SM BKN...,72055399999.csv

In [201]:
df.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL', 'WND', 'CIG',
       'VIS', 'TMP', 'DEW', 'SLP', 'REM', 'source_file'],
      dtype='object')

In [202]:
len(df.columns)

18

In [203]:
df.to_csv(target_path+"2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_21K_1.csv", index=False)

In [17]:
df.to_csv(target_path+"2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_21K_1_22cols.csv", index=False)